// apps/rider-mobile/constants/mekongLocations.js

const loc = ({
  provinceSlug,
  locationSlug,
  name,
  fullAddress,
  shortAddress,
  maskedAddress,
  lat,
  lng,
  keywords,
}) => ({
  placeId: `goviet247:mekong:${provinceSlug}:${locationSlug}`,
  name,
  fullAddress,
  shortAddress,
  maskedAddress,
  lat,
  lng,
  keywords,
});

export const MEKONG_LOCATIONS = [
  // =========================
  // LONG AN
  // =========================
  loc({
    provinceSlug: "long-an",
    locationSlug: "tan-an",
    name: "Tân An - Long An",
    fullAddress: "Tân An, Long An, Việt Nam",
    shortAddress: "Tân An",
    maskedAddress: "Tân An, Long An",
    lat: 10.5333,
    lng: 106.4167,
    keywords: ["tan an", "tân an", "long an", "xe đi tân an", "xe đi long an"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "ben-luc",
    name: "Bến Lức - Long An",
    fullAddress: "Bến Lức, Long An, Việt Nam",
    shortAddress: "Bến Lức",
    maskedAddress: "Bến Lức, Long An",
    lat: 10.6429,
    lng: 106.4785,
    keywords: ["ben luc", "bến lức", "long an", "xe đi bến lức"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "duc-hoa",
    name: "Đức Hòa - Long An",
    fullAddress: "Đức Hòa, Long An, Việt Nam",
    shortAddress: "Đức Hòa",
    maskedAddress: "Đức Hòa, Long An",
    lat: 10.8784,
    lng: 106.4243,
    keywords: ["duc hoa", "đức hòa", "long an", "xe đi đức hòa"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "duc-hue",
    name: "Đức Huệ - Long An",
    fullAddress: "Đức Huệ, Long An, Việt Nam",
    shortAddress: "Đức Huệ",
    maskedAddress: "Đức Huệ, Long An",
    lat: 10.8644,
    lng: 106.2636,
    keywords: ["duc hue", "đức huệ", "long an", "xe đi đức huệ"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "can-giuoc",
    name: "Cần Giuộc - Long An",
    fullAddress: "Cần Giuộc, Long An, Việt Nam",
    shortAddress: "Cần Giuộc",
    maskedAddress: "Cần Giuộc, Long An",
    lat: 10.6066,
    lng: 106.6714,
    keywords: ["can giuoc", "cần giuộc", "long an", "xe đi cần giuộc"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "can-duoc",
    name: "Cần Đước - Long An",
    fullAddress: "Cần Đước, Long An, Việt Nam",
    shortAddress: "Cần Đước",
    maskedAddress: "Cần Đước, Long An",
    lat: 10.5419,
    lng: 106.5965,
    keywords: ["can duoc", "cần đước", "long an", "xe đi cần đước"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "thu-thua",
    name: "Thủ Thừa - Long An",
    fullAddress: "Thủ Thừa, Long An, Việt Nam",
    shortAddress: "Thủ Thừa",
    maskedAddress: "Thủ Thừa, Long An",
    lat: 10.5934,
    lng: 106.4049,
    keywords: ["thu thua", "thủ thừa", "long an", "xe đi thủ thừa"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "tan-tru",
    name: "Tân Trụ - Long An",
    fullAddress: "Tân Trụ, Long An, Việt Nam",
    shortAddress: "Tân Trụ",
    maskedAddress: "Tân Trụ, Long An",
    lat: 10.5167,
    lng: 106.5167,
    keywords: ["tan tru", "tân trụ", "long an", "xe đi tân trụ"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "chau-thanh",
    name: "Châu Thành - Long An",
    fullAddress: "Châu Thành, Long An, Việt Nam",
    shortAddress: "Châu Thành",
    maskedAddress: "Châu Thành, Long An",
    lat: 10.4529,
    lng: 106.4897,
    keywords: [
      "chau thanh",
      "châu thành",
      "long an",
      "xe đi châu thành long an",
    ],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "tan-hung",
    name: "Tân Hưng - Long An",
    fullAddress: "Tân Hưng, Long An, Việt Nam",
    shortAddress: "Tân Hưng",
    maskedAddress: "Tân Hưng, Long An",
    lat: 10.8306,
    lng: 105.6881,
    keywords: ["tan hung", "tân hưng", "long an", "xe đi tân hưng"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "vinh-hung",
    name: "Vĩnh Hưng - Long An",
    fullAddress: "Vĩnh Hưng, Long An, Việt Nam",
    shortAddress: "Vĩnh Hưng",
    maskedAddress: "Vĩnh Hưng, Long An",
    lat: 10.8908,
    lng: 105.7847,
    keywords: ["vinh hung", "vĩnh hưng", "long an", "xe đi vĩnh hưng"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "moc-hoa",
    name: "Mộc Hóa - Long An",
    fullAddress: "Mộc Hóa, Long An, Việt Nam",
    shortAddress: "Mộc Hóa",
    maskedAddress: "Mộc Hóa, Long An",
    lat: 10.7583,
    lng: 105.9317,
    keywords: ["moc hoa", "mộc hóa", "long an", "xe đi mộc hóa"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "tan-thanh",
    name: "Tân Thạnh - Long An",
    fullAddress: "Tân Thạnh, Long An, Việt Nam",
    shortAddress: "Tân Thạnh",
    maskedAddress: "Tân Thạnh, Long An",
    lat: 10.6031,
    lng: 106.0256,
    keywords: ["tan thanh", "tân thạnh", "long an", "xe đi tân thạnh"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "thanh-hoa",
    name: "Thạnh Hóa - Long An",
    fullAddress: "Thạnh Hóa, Long An, Việt Nam",
    shortAddress: "Thạnh Hóa",
    maskedAddress: "Thạnh Hóa, Long An",
    lat: 10.6458,
    lng: 106.1806,
    keywords: ["thanh hoa", "thạnh hóa", "long an", "xe đi thạnh hóa"],
  }),
  loc({
    provinceSlug: "long-an",
    locationSlug: "kien-tuong",
    name: "Kiến Tường - Long An",
    fullAddress: "Kiến Tường, Long An, Việt Nam",
    shortAddress: "Kiến Tường",
    maskedAddress: "Kiến Tường, Long An",
    lat: 10.7772,
    lng: 105.9497,
    keywords: ["kien tuong", "kiến tường", "long an", "xe đi kiến tường"],
  }),

  // =========================
  // TIỀN GIANG
  // =========================
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "my-tho",
    name: "Mỹ Tho - Tiền Giang",
    fullAddress: "Mỹ Tho, Tiền Giang, Việt Nam",
    shortAddress: "Mỹ Tho",
    maskedAddress: "Mỹ Tho, Tiền Giang",
    lat: 10.36,
    lng: 106.36,
    keywords: ["my tho", "mỹ tho", "tien giang", "tiền giang", "xe đi mỹ tho"],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "go-cong",
    name: "Gò Công - Tiền Giang",
    fullAddress: "Gò Công, Tiền Giang, Việt Nam",
    shortAddress: "Gò Công",
    maskedAddress: "Gò Công, Tiền Giang",
    lat: 10.3672,
    lng: 106.6753,
    keywords: [
      "go cong",
      "gò công",
      "tien giang",
      "tiền giang",
      "xe đi gò công",
    ],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "cai-lay",
    name: "Cai Lậy - Tiền Giang",
    fullAddress: "Cai Lậy, Tiền Giang, Việt Nam",
    shortAddress: "Cai Lậy",
    maskedAddress: "Cai Lậy, Tiền Giang",
    lat: 10.4058,
    lng: 106.1189,
    keywords: [
      "cai lay",
      "cai lậy",
      "tien giang",
      "tiền giang",
      "xe đi cai lậy",
    ],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "cai-be",
    name: "Cái Bè - Tiền Giang",
    fullAddress: "Cái Bè, Tiền Giang, Việt Nam",
    shortAddress: "Cái Bè",
    maskedAddress: "Cái Bè, Tiền Giang",
    lat: 10.3333,
    lng: 106.0333,
    keywords: ["cai be", "cái bè", "tien giang", "tiền giang", "xe đi cái bè"],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "chau-thanh",
    name: "Châu Thành - Tiền Giang",
    fullAddress: "Châu Thành, Tiền Giang, Việt Nam",
    shortAddress: "Châu Thành",
    maskedAddress: "Châu Thành, Tiền Giang",
    lat: 10.3861,
    lng: 106.3267,
    keywords: [
      "chau thanh",
      "châu thành",
      "tien giang",
      "tiền giang",
      "xe đi châu thành tiền giang",
    ],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "cho-gao",
    name: "Chợ Gạo - Tiền Giang",
    fullAddress: "Chợ Gạo, Tiền Giang, Việt Nam",
    shortAddress: "Chợ Gạo",
    maskedAddress: "Chợ Gạo, Tiền Giang",
    lat: 10.3497,
    lng: 106.4653,
    keywords: [
      "cho gao",
      "chợ gạo",
      "tien giang",
      "tiền giang",
      "xe đi chợ gạo",
    ],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "tan-phuoc",
    name: "Tân Phước - Tiền Giang",
    fullAddress: "Tân Phước, Tiền Giang, Việt Nam",
    shortAddress: "Tân Phước",
    maskedAddress: "Tân Phước, Tiền Giang",
    lat: 10.5142,
    lng: 106.2333,
    keywords: [
      "tan phuoc",
      "tân phước",
      "tien giang",
      "tiền giang",
      "xe đi tân phước",
    ],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "go-cong-dong",
    name: "Gò Công Đông - Tiền Giang",
    fullAddress: "Gò Công Đông, Tiền Giang, Việt Nam",
    shortAddress: "Gò Công Đông",
    maskedAddress: "Gò Công Đông, Tiền Giang",
    lat: 10.335,
    lng: 106.728,
    keywords: [
      "go cong dong",
      "gò công đông",
      "tien giang",
      "tiền giang",
      "xe đi gò công đông",
    ],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "go-cong-tay",
    name: "Gò Công Tây - Tiền Giang",
    fullAddress: "Gò Công Tây, Tiền Giang, Việt Nam",
    shortAddress: "Gò Công Tây",
    maskedAddress: "Gò Công Tây, Tiền Giang",
    lat: 10.355,
    lng: 106.604,
    keywords: [
      "go cong tay",
      "gò công tây",
      "tien giang",
      "tiền giang",
      "xe đi gò công tây",
    ],
  }),
  loc({
    provinceSlug: "tien-giang",
    locationSlug: "tan-phu-dong",
    name: "Tân Phú Đông - Tiền Giang",
    fullAddress: "Tân Phú Đông, Tiền Giang, Việt Nam",
    shortAddress: "Tân Phú Đông",
    maskedAddress: "Tân Phú Đông, Tiền Giang",
    lat: 10.245,
    lng: 106.76,
    keywords: [
      "tan phu dong",
      "tân phú đông",
      "tien giang",
      "tiền giang",
      "xe đi tân phú đông",
    ],
  }),

  // =========================
  // BẾN TRE
  // =========================
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "ben-tre",
    name: "Bến Tre - Bến Tre",
    fullAddress: "Bến Tre, Bến Tre, Việt Nam",
    shortAddress: "Bến Tre",
    maskedAddress: "Bến Tre",
    lat: 10.2433,
    lng: 106.3756,
    keywords: ["ben tre", "bến tre", "xe đi bến tre"],
  }),
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "ba-tri",
    name: "Ba Tri - Bến Tre",
    fullAddress: "Ba Tri, Bến Tre, Việt Nam",
    shortAddress: "Ba Tri",
    maskedAddress: "Ba Tri, Bến Tre",
    lat: 10.0444,
    lng: 106.5903,
    keywords: ["ba tri", "bến tre", "xe đi ba tri"],
  }),
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "binh-dai",
    name: "Bình Đại - Bến Tre",
    fullAddress: "Bình Đại, Bến Tre, Việt Nam",
    shortAddress: "Bình Đại",
    maskedAddress: "Bình Đại, Bến Tre",
    lat: 10.1942,
    lng: 106.6922,
    keywords: ["binh dai", "bình đại", "bến tre", "xe đi bình đại"],
  }),
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "chau-thanh",
    name: "Châu Thành - Bến Tre",
    fullAddress: "Châu Thành, Bến Tre, Việt Nam",
    shortAddress: "Châu Thành",
    maskedAddress: "Châu Thành, Bến Tre",
    lat: 10.2925,
    lng: 106.3086,
    keywords: [
      "chau thanh",
      "châu thành",
      "bến tre",
      "xe đi châu thành bến tre",
    ],
  }),
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "cho-lach",
    name: "Chợ Lách - Bến Tre",
    fullAddress: "Chợ Lách, Bến Tre, Việt Nam",
    shortAddress: "Chợ Lách",
    maskedAddress: "Chợ Lách, Bến Tre",
    lat: 10.2608,
    lng: 106.1181,
    keywords: ["cho lach", "chợ lách", "bến tre", "xe đi chợ lách"],
  }),
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "giong-trom",
    name: "Giồng Trôm - Bến Tre",
    fullAddress: "Giồng Trôm, Bến Tre, Việt Nam",
    shortAddress: "Giồng Trôm",
    maskedAddress: "Giồng Trôm, Bến Tre",
    lat: 10.1586,
    lng: 106.4703,
    keywords: ["giong trom", "giồng trôm", "bến tre", "xe đi giồng trôm"],
  }),
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "mo-cay-bac",
    name: "Mỏ Cày Bắc - Bến Tre",
    fullAddress: "Mỏ Cày Bắc, Bến Tre, Việt Nam",
    shortAddress: "Mỏ Cày Bắc",
    maskedAddress: "Mỏ Cày Bắc, Bến Tre",
    lat: 10.17,
    lng: 106.3,
    keywords: ["mo cay bac", "mỏ cày bắc", "bến tre", "xe đi mỏ cày bắc"],
  }),
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "mo-cay-nam",
    name: "Mỏ Cày Nam - Bến Tre",
    fullAddress: "Mỏ Cày Nam, Bến Tre, Việt Nam",
    shortAddress: "Mỏ Cày Nam",
    maskedAddress: "Mỏ Cày Nam, Bến Tre",
    lat: 10.1167,
    lng: 106.3333,
    keywords: ["mo cay nam", "mỏ cày nam", "bến tre", "xe đi mỏ cày nam"],
  }),
  loc({
    provinceSlug: "ben-tre",
    locationSlug: "thanh-phu",
    name: "Thạnh Phú - Bến Tre",
    fullAddress: "Thạnh Phú, Bến Tre, Việt Nam",
    shortAddress: "Thạnh Phú",
    maskedAddress: "Thạnh Phú, Bến Tre",
    lat: 9.9297,
    lng: 106.5431,
    keywords: ["thanh phu", "thạnh phú", "bến tre", "xe đi thạnh phú"],
  }),

  // =========================
  // TRÀ VINH
  // =========================
  loc({
    provinceSlug: "tra-vinh",
    locationSlug: "tra-vinh",
    name: "Trà Vinh - Trà Vinh",
    fullAddress: "Trà Vinh, Trà Vinh, Việt Nam",
    shortAddress: "Trà Vinh",
    maskedAddress: "Trà Vinh",
    lat: 9.9347,
    lng: 106.3453,
    keywords: ["tra vinh", "trà vinh", "xe đi trà vinh"],
  }),
  loc({
    provinceSlug: "tra-vinh",
    locationSlug: "cang-long",
    name: "Càng Long - Trà Vinh",
    fullAddress: "Càng Long, Trà Vinh, Việt Nam",
    shortAddress: "Càng Long",
    maskedAddress: "Càng Long, Trà Vinh",
    lat: 9.98,
    lng: 106.21,
    keywords: ["cang long", "càng long", "trà vinh", "xe đi càng long"],
  }),
  loc({
    provinceSlug: "tra-vinh",
    locationSlug: "cau-ke",
    name: "Cầu Kè - Trà Vinh",
    fullAddress: "Cầu Kè, Trà Vinh, Việt Nam",
    shortAddress: "Cầu Kè",
    maskedAddress: "Cầu Kè, Trà Vinh",
    lat: 9.8675,
    lng: 106.0797,
    keywords: ["cau ke", "cầu kè", "trà vinh", "xe đi cầu kè"],
  }),
  loc({
    provinceSlug: "tra-vinh",
    locationSlug: "cau-ngang",
    name: "Cầu Ngang - Trà Vinh",
    fullAddress: "Cầu Ngang, Trà Vinh, Việt Nam",
    shortAddress: "Cầu Ngang",
    maskedAddress: "Cầu Ngang, Trà Vinh",
    lat: 9.77,
    lng: 106.44,
    keywords: ["cau ngang", "cầu ngang", "trà vinh", "xe đi cầu ngang"],
  }),
  loc({
    provinceSlug: "tra-vinh",
    locationSlug: "chau-thanh",
    name: "Châu Thành - Trà Vinh",
    fullAddress: "Châu Thành, Trà Vinh, Việt Nam",
    shortAddress: "Châu Thành",
    maskedAddress: "Châu Thành, Trà Vinh",
    lat: 9.922,
    lng: 106.37,
    keywords: [
      "chau thanh",
      "châu thành",
      "trà vinh",
      "xe đi châu thành trà vinh",
    ],
  }),
  loc({
    provinceSlug: "tra-vinh",
    locationSlug: "duyen-hai",
    name: "Duyên Hải - Trà Vinh",
    fullAddress: "Duyên Hải, Trà Vinh, Việt Nam",
    shortAddress: "Duyên Hải",
    maskedAddress: "Duyên Hải, Trà Vinh",
    lat: 9.6344,
    lng: 106.4878,
    keywords: ["duyen hai", "duyên hải", "trà vinh", "xe đi duyên hải"],
  }),
  loc({
    provinceSlug: "tra-vinh",
    locationSlug: "tieu-can",
    name: "Tiểu Cần - Trà Vinh",
    fullAddress: "Tiểu Cần, Trà Vinh, Việt Nam",
    shortAddress: "Tiểu Cần",
    maskedAddress: "Tiểu Cần, Trà Vinh",
    lat: 9.8031,
    lng: 106.2058,
    keywords: ["tieu can", "tiểu cần", "trà vinh", "xe đi tiểu cần"],
  }),
  loc({
    provinceSlug: "tra-vinh",
    locationSlug: "tra-cu",
    name: "Trà Cú - Trà Vinh",
    fullAddress: "Trà Cú, Trà Vinh, Việt Nam",
    shortAddress: "Trà Cú",
    maskedAddress: "Trà Cú, Trà Vinh",
    lat: 9.6972,
    lng: 106.2942,
    keywords: ["tra cu", "trà cú", "trà vinh", "xe đi trà cú"],
  }),

  // =========================
  // VĨNH LONG
  // =========================
  loc({
    provinceSlug: "vinh-long",
    locationSlug: "vinh-long",
    name: "Vĩnh Long - Vĩnh Long",
    fullAddress: "Vĩnh Long, Vĩnh Long, Việt Nam",
    shortAddress: "Vĩnh Long",
    maskedAddress: "Vĩnh Long",
    lat: 10.2537,
    lng: 105.9722,
    keywords: ["vinh long", "vĩnh long", "xe đi vĩnh long"],
  }),
  loc({
    provinceSlug: "vinh-long",
    locationSlug: "binh-minh",
    name: "Bình Minh - Vĩnh Long",
    fullAddress: "Bình Minh, Vĩnh Long, Việt Nam",
    shortAddress: "Bình Minh",
    maskedAddress: "Bình Minh, Vĩnh Long",
    lat: 10.0689,
    lng: 105.8228,
    keywords: ["binh minh", "bình minh", "vĩnh long", "xe đi bình minh"],
  }),
  loc({
    provinceSlug: "vinh-long",
    locationSlug: "binh-tan",
    name: "Bình Tân - Vĩnh Long",
    fullAddress: "Bình Tân, Vĩnh Long, Việt Nam",
    shortAddress: "Bình Tân",
    maskedAddress: "Bình Tân, Vĩnh Long",
    lat: 10.0975,
    lng: 105.93,
    keywords: ["binh tan", "bình tân", "vĩnh long", "xe đi bình tân vĩnh long"],
  }),
  loc({
    provinceSlug: "vinh-long",
    locationSlug: "long-ho",
    name: "Long Hồ - Vĩnh Long",
    fullAddress: "Long Hồ, Vĩnh Long, Việt Nam",
    shortAddress: "Long Hồ",
    maskedAddress: "Long Hồ, Vĩnh Long",
    lat: 10.2167,
    lng: 105.9833,
    keywords: ["long ho", "long hồ", "vĩnh long", "xe đi long hồ"],
  }),
  loc({
    provinceSlug: "vinh-long",
    locationSlug: "mang-thit",
    name: "Mang Thít - Vĩnh Long",
    fullAddress: "Mang Thít, Vĩnh Long, Việt Nam",
    shortAddress: "Mang Thít",
    maskedAddress: "Mang Thít, Vĩnh Long",
    lat: 10.1875,
    lng: 106.095,
    keywords: ["mang thit", "mang thít", "vĩnh long", "xe đi mang thít"],
  }),
  loc({
    provinceSlug: "vinh-long",
    locationSlug: "tam-binh",
    name: "Tam Bình - Vĩnh Long",
    fullAddress: "Tam Bình, Vĩnh Long, Việt Nam",
    shortAddress: "Tam Bình",
    maskedAddress: "Tam Bình, Vĩnh Long",
    lat: 10.0458,
    lng: 105.9708,
    keywords: ["tam binh", "tam bình", "vĩnh long", "xe đi tam bình"],
  }),
  loc({
    provinceSlug: "vinh-long",
    locationSlug: "tra-on",
    name: "Trà Ôn - Vĩnh Long",
    fullAddress: "Trà Ôn, Vĩnh Long, Việt Nam",
    shortAddress: "Trà Ôn",
    maskedAddress: "Trà Ôn, Vĩnh Long",
    lat: 9.9625,
    lng: 106.0339,
    keywords: ["tra on", "trà ôn", "vĩnh long", "xe đi trà ôn"],
  }),
  loc({
    provinceSlug: "vinh-long",
    locationSlug: "vung-liem",
    name: "Vũng Liêm - Vĩnh Long",
    fullAddress: "Vũng Liêm, Vĩnh Long, Việt Nam",
    shortAddress: "Vũng Liêm",
    maskedAddress: "Vũng Liêm, Vĩnh Long",
    lat: 10.0892,
    lng: 106.19,
    keywords: ["vung liem", "vũng liêm", "vĩnh long", "xe đi vũng liêm"],
  }),

  // =========================
  // ĐỒNG THÁP
  // =========================
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "cao-lanh",
    name: "Cao Lãnh - Đồng Tháp",
    fullAddress: "Cao Lãnh, Đồng Tháp, Việt Nam",
    shortAddress: "Cao Lãnh",
    maskedAddress: "Cao Lãnh, Đồng Tháp",
    lat: 10.4602,
    lng: 105.6329,
    keywords: [
      "cao lanh",
      "cao lãnh",
      "dong thap",
      "đồng tháp",
      "xe đi cao lãnh",
    ],
  }),
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "sa-dec",
    name: "Sa Đéc - Đồng Tháp",
    fullAddress: "Sa Đéc, Đồng Tháp, Việt Nam",
    shortAddress: "Sa Đéc",
    maskedAddress: "Sa Đéc, Đồng Tháp",
    lat: 10.2908,
    lng: 105.7564,
    keywords: ["sa dec", "sa đéc", "dong thap", "đồng tháp", "xe đi sa đéc"],
  }),
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "hong-ngu",
    name: "Hồng Ngự - Đồng Tháp",
    fullAddress: "Hồng Ngự, Đồng Tháp, Việt Nam",
    shortAddress: "Hồng Ngự",
    maskedAddress: "Hồng Ngự, Đồng Tháp",
    lat: 10.8,
    lng: 105.3333,
    keywords: [
      "hong ngu",
      "hồng ngự",
      "dong thap",
      "đồng tháp",
      "xe đi hồng ngự",
    ],
  }),
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "lai-vung",
    name: "Lai Vung - Đồng Tháp",
    fullAddress: "Lai Vung, Đồng Tháp, Việt Nam",
    shortAddress: "Lai Vung",
    maskedAddress: "Lai Vung, Đồng Tháp",
    lat: 10.2406,
    lng: 105.6631,
    keywords: ["lai vung", "dong thap", "đồng tháp", "xe đi lai vung"],
  }),
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "lap-vo",
    name: "Lấp Vò - Đồng Tháp",
    fullAddress: "Lấp Vò, Đồng Tháp, Việt Nam",
    shortAddress: "Lấp Vò",
    maskedAddress: "Lấp Vò, Đồng Tháp",
    lat: 10.36,
    lng: 105.52,
    keywords: ["lap vo", "lấp vò", "dong thap", "đồng tháp", "xe đi lấp vò"],
  }),
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "tam-nong",
    name: "Tam Nông - Đồng Tháp",
    fullAddress: "Tam Nông, Đồng Tháp, Việt Nam",
    shortAddress: "Tam Nông",
    maskedAddress: "Tam Nông, Đồng Tháp",
    lat: 10.705,
    lng: 105.525,
    keywords: [
      "tam nong",
      "tam nông",
      "dong thap",
      "đồng tháp",
      "xe đi tam nông",
    ],
  }),
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "thanh-binh",
    name: "Thanh Bình - Đồng Tháp",
    fullAddress: "Thanh Bình, Đồng Tháp, Việt Nam",
    shortAddress: "Thanh Bình",
    maskedAddress: "Thanh Bình, Đồng Tháp",
    lat: 10.6017,
    lng: 105.4783,
    keywords: [
      "thanh binh",
      "thanh bình",
      "dong thap",
      "đồng tháp",
      "xe đi thanh bình",
    ],
  }),
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "thap-muoi",
    name: "Tháp Mười - Đồng Tháp",
    fullAddress: "Tháp Mười, Đồng Tháp, Việt Nam",
    shortAddress: "Tháp Mười",
    maskedAddress: "Tháp Mười, Đồng Tháp",
    lat: 10.5433,
    lng: 105.8592,
    keywords: [
      "thap muoi",
      "tháp mười",
      "dong thap",
      "đồng tháp",
      "xe đi tháp mười",
    ],
  }),
  loc({
    provinceSlug: "dong-thap",
    locationSlug: "chau-thanh",
    name: "Châu Thành - Đồng Tháp",
    fullAddress: "Châu Thành, Đồng Tháp, Việt Nam",
    shortAddress: "Châu Thành",
    maskedAddress: "Châu Thành, Đồng Tháp",
    lat: 10.225,
    lng: 105.7917,
    keywords: [
      "chau thanh",
      "châu thành",
      "dong thap",
      "đồng tháp",
      "xe đi châu thành đồng tháp",
    ],
  }),

  // =========================
  // AN GIANG
  // =========================
  loc({
    provinceSlug: "an-giang",
    locationSlug: "long-xuyen",
    name: "Long Xuyên - An Giang",
    fullAddress: "Long Xuyên, An Giang, Việt Nam",
    shortAddress: "Long Xuyên",
    maskedAddress: "Long Xuyên, An Giang",
    lat: 10.3864,
    lng: 105.4352,
    keywords: ["long xuyen", "long xuyên", "an giang", "xe đi long xuyên"],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "chau-doc",
    name: "Châu Đốc - An Giang",
    fullAddress: "Châu Đốc, An Giang, Việt Nam",
    shortAddress: "Châu Đốc",
    maskedAddress: "Châu Đốc, An Giang",
    lat: 10.7,
    lng: 105.1167,
    keywords: ["chau doc", "châu đốc", "an giang", "xe đi châu đốc"],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "tinh-bien",
    name: "Tịnh Biên - An Giang",
    fullAddress: "Tịnh Biên, An Giang, Việt Nam",
    shortAddress: "Tịnh Biên",
    maskedAddress: "Tịnh Biên, An Giang",
    lat: 10.6067,
    lng: 104.955,
    keywords: ["tinh bien", "tịnh biên", "an giang", "xe đi tịnh biên"],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "tri-ton",
    name: "Tri Tôn - An Giang",
    fullAddress: "Tri Tôn, An Giang, Việt Nam",
    shortAddress: "Tri Tôn",
    maskedAddress: "Tri Tôn, An Giang",
    lat: 10.4142,
    lng: 104.9614,
    keywords: ["tri ton", "tri tôn", "an giang", "xe đi tri tôn"],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "chau-phu",
    name: "Châu Phú - An Giang",
    fullAddress: "Châu Phú, An Giang, Việt Nam",
    shortAddress: "Châu Phú",
    maskedAddress: "Châu Phú, An Giang",
    lat: 10.57,
    lng: 105.235,
    keywords: ["chau phu", "châu phú", "an giang", "xe đi châu phú"],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "chau-thanh",
    name: "Châu Thành - An Giang",
    fullAddress: "Châu Thành, An Giang, Việt Nam",
    shortAddress: "Châu Thành",
    maskedAddress: "Châu Thành, An Giang",
    lat: 10.4042,
    lng: 105.265,
    keywords: [
      "chau thanh",
      "châu thành",
      "an giang",
      "xe đi châu thành an giang",
    ],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "tan-chau",
    name: "Tân Châu - An Giang",
    fullAddress: "Tân Châu, An Giang, Việt Nam",
    shortAddress: "Tân Châu",
    maskedAddress: "Tân Châu, An Giang",
    lat: 10.8014,
    lng: 105.2386,
    keywords: ["tan chau", "tân châu", "an giang", "xe đi tân châu"],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "an-phu",
    name: "An Phú - An Giang",
    fullAddress: "An Phú, An Giang, Việt Nam",
    shortAddress: "An Phú",
    maskedAddress: "An Phú, An Giang",
    lat: 10.815,
    lng: 105.0883,
    keywords: ["an phu", "an phú", "an giang", "xe đi an phú"],
  }),

  // =========================
  // KIÊN GIANG
  // =========================
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "rach-gia",
    name: "Rạch Giá - Kiên Giang",
    fullAddress: "Rạch Giá, Kiên Giang, Việt Nam",
    shortAddress: "Rạch Giá",
    maskedAddress: "Rạch Giá, Kiên Giang",
    lat: 10.0125,
    lng: 105.0809,
    keywords: [
      "rach gia",
      "rạch giá",
      "kien giang",
      "kiên giang",
      "xe đi rạch giá",
    ],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "ha-tien",
    name: "Hà Tiên - Kiên Giang",
    fullAddress: "Hà Tiên, Kiên Giang, Việt Nam",
    shortAddress: "Hà Tiên",
    maskedAddress: "Hà Tiên, Kiên Giang",
    lat: 10.3831,
    lng: 104.4875,
    keywords: [
      "ha tien",
      "hà tiên",
      "kien giang",
      "kiên giang",
      "xe đi hà tiên",
    ],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "phu-quoc",
    name: "Phú Quốc - Kiên Giang",
    fullAddress: "Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "Phú Quốc",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.2899,
    lng: 103.984,
    keywords: [
      "phu quoc",
      "phú quốc",
      "kien giang",
      "kiên giang",
      "xe đi phú quốc",
    ],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "kien-luong",
    name: "Kiên Lương - Kiên Giang",
    fullAddress: "Kiên Lương, Kiên Giang, Việt Nam",
    shortAddress: "Kiên Lương",
    maskedAddress: "Kiên Lương, Kiên Giang",
    lat: 10.2875,
    lng: 104.6469,
    keywords: [
      "kien luong",
      "kiên lương",
      "kien giang",
      "kiên giang",
      "xe đi kiên lương",
    ],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "hon-dat",
    name: "Hòn Đất - Kiên Giang",
    fullAddress: "Hòn Đất, Kiên Giang, Việt Nam",
    shortAddress: "Hòn Đất",
    maskedAddress: "Hòn Đất, Kiên Giang",
    lat: 10.1833,
    lng: 104.95,
    keywords: [
      "hon dat",
      "hòn đất",
      "kien giang",
      "kiên giang",
      "xe đi hòn đất",
    ],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "giong-rieng",
    name: "Giồng Riềng - Kiên Giang",
    fullAddress: "Giồng Riềng, Kiên Giang, Việt Nam",
    shortAddress: "Giồng Riềng",
    maskedAddress: "Giồng Riềng, Kiên Giang",
    lat: 9.9125,
    lng: 105.3186,
    keywords: [
      "giong rieng",
      "giồng riềng",
      "kien giang",
      "kiên giang",
      "xe đi giồng riềng",
    ],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "tan-hiep",
    name: "Tân Hiệp - Kiên Giang",
    fullAddress: "Tân Hiệp, Kiên Giang, Việt Nam",
    shortAddress: "Tân Hiệp",
    maskedAddress: "Tân Hiệp, Kiên Giang",
    lat: 10.1178,
    lng: 105.285,
    keywords: [
      "tan hiep",
      "tân hiệp",
      "kien giang",
      "kiên giang",
      "xe đi tân hiệp",
    ],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "an-bien",
    name: "An Biên - Kiên Giang",
    fullAddress: "An Biên, Kiên Giang, Việt Nam",
    shortAddress: "An Biên",
    maskedAddress: "An Biên, Kiên Giang",
    lat: 9.8083,
    lng: 105.055,
    keywords: [
      "an bien",
      "an biên",
      "kien giang",
      "kiên giang",
      "xe đi an biên",
    ],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "an-minh",
    name: "An Minh - Kiên Giang",
    fullAddress: "An Minh, Kiên Giang, Việt Nam",
    shortAddress: "An Minh",
    maskedAddress: "An Minh, Kiên Giang",
    lat: 9.6686,
    lng: 104.9519,
    keywords: ["an minh", "kien giang", "kiên giang", "xe đi an minh"],
  }),

  // =========================
  // HẬU GIANG
  // =========================
  loc({
    provinceSlug: "hau-giang",
    locationSlug: "vi-thanh",
    name: "Vị Thanh - Hậu Giang",
    fullAddress: "Vị Thanh, Hậu Giang, Việt Nam",
    shortAddress: "Vị Thanh",
    maskedAddress: "Vị Thanh, Hậu Giang",
    lat: 9.7844,
    lng: 105.4701,
    keywords: [
      "vi thanh",
      "vị thanh",
      "hau giang",
      "hậu giang",
      "xe đi vị thanh",
    ],
  }),
  loc({
    provinceSlug: "hau-giang",
    locationSlug: "nga-bay",
    name: "Ngã Bảy - Hậu Giang",
    fullAddress: "Ngã Bảy, Hậu Giang, Việt Nam",
    shortAddress: "Ngã Bảy",
    maskedAddress: "Ngã Bảy, Hậu Giang",
    lat: 9.8175,
    lng: 105.8175,
    keywords: ["nga bay", "ngã bảy", "hau giang", "hậu giang", "xe đi ngã bảy"],
  }),
  loc({
    provinceSlug: "hau-giang",
    locationSlug: "chau-thanh-a",
    name: "Châu Thành A - Hậu Giang",
    fullAddress: "Châu Thành A, Hậu Giang, Việt Nam",
    shortAddress: "Châu Thành A",
    maskedAddress: "Châu Thành A, Hậu Giang",
    lat: 9.93,
    lng: 105.64,
    keywords: [
      "chau thanh a",
      "châu thành a",
      "hau giang",
      "hậu giang",
      "xe đi châu thành a",
    ],
  }),
  loc({
    provinceSlug: "hau-giang",
    locationSlug: "chau-thanh",
    name: "Châu Thành - Hậu Giang",
    fullAddress: "Châu Thành, Hậu Giang, Việt Nam",
    shortAddress: "Châu Thành",
    maskedAddress: "Châu Thành, Hậu Giang",
    lat: 9.92,
    lng: 105.84,
    keywords: [
      "chau thanh",
      "châu thành",
      "hau giang",
      "hậu giang",
      "xe đi châu thành hậu giang",
    ],
  }),
  loc({
    provinceSlug: "hau-giang",
    locationSlug: "long-my",
    name: "Long Mỹ - Hậu Giang",
    fullAddress: "Long Mỹ, Hậu Giang, Việt Nam",
    shortAddress: "Long Mỹ",
    maskedAddress: "Long Mỹ, Hậu Giang",
    lat: 9.6817,
    lng: 105.5722,
    keywords: ["long my", "long mỹ", "hau giang", "hậu giang", "xe đi long mỹ"],
  }),
  loc({
    provinceSlug: "hau-giang",
    locationSlug: "phung-hiep",
    name: "Phụng Hiệp - Hậu Giang",
    fullAddress: "Phụng Hiệp, Hậu Giang, Việt Nam",
    shortAddress: "Phụng Hiệp",
    maskedAddress: "Phụng Hiệp, Hậu Giang",
    lat: 9.7833,
    lng: 105.7333,
    keywords: [
      "phung hiep",
      "phụng hiệp",
      "hau giang",
      "hậu giang",
      "xe đi phụng hiệp",
    ],
  }),
  loc({
    provinceSlug: "hau-giang",
    locationSlug: "vi-thuy",
    name: "Vị Thủy - Hậu Giang",
    fullAddress: "Vị Thủy, Hậu Giang, Việt Nam",
    shortAddress: "Vị Thủy",
    maskedAddress: "Vị Thủy, Hậu Giang",
    lat: 9.7583,
    lng: 105.525,
    keywords: ["vi thuy", "vị thủy", "hau giang", "hậu giang", "xe đi vị thủy"],
  }),

  // =========================
  // SÓC TRĂNG
  // =========================
  loc({
    provinceSlug: "soc-trang",
    locationSlug: "soc-trang",
    name: "Sóc Trăng - Sóc Trăng",
    fullAddress: "Sóc Trăng, Sóc Trăng, Việt Nam",
    shortAddress: "Sóc Trăng",
    maskedAddress: "Sóc Trăng",
    lat: 9.6025,
    lng: 105.9739,
    keywords: ["soc trang", "sóc trăng", "xe đi sóc trăng"],
  }),
  loc({
    provinceSlug: "soc-trang",
    locationSlug: "my-xuyen",
    name: "Mỹ Xuyên - Sóc Trăng",
    fullAddress: "Mỹ Xuyên, Sóc Trăng, Việt Nam",
    shortAddress: "Mỹ Xuyên",
    maskedAddress: "Mỹ Xuyên, Sóc Trăng",
    lat: 9.565,
    lng: 105.985,
    keywords: ["my xuyen", "mỹ xuyên", "sóc trăng", "xe đi mỹ xuyên"],
  }),
  loc({
    provinceSlug: "soc-trang",
    locationSlug: "my-tu",
    name: "Mỹ Tú - Sóc Trăng",
    fullAddress: "Mỹ Tú, Sóc Trăng, Việt Nam",
    shortAddress: "Mỹ Tú",
    maskedAddress: "Mỹ Tú, Sóc Trăng",
    lat: 9.62,
    lng: 105.8067,
    keywords: ["my tu", "mỹ tú", "sóc trăng", "xe đi mỹ tú"],
  }),
  loc({
    provinceSlug: "soc-trang",
    locationSlug: "ke-sach",
    name: "Kế Sách - Sóc Trăng",
    fullAddress: "Kế Sách, Sóc Trăng, Việt Nam",
    shortAddress: "Kế Sách",
    maskedAddress: "Kế Sách, Sóc Trăng",
    lat: 9.825,
    lng: 105.9417,
    keywords: ["ke sach", "kế sách", "sóc trăng", "xe đi kế sách"],
  }),
  loc({
    provinceSlug: "soc-trang",
    locationSlug: "long-phu",
    name: "Long Phú - Sóc Trăng",
    fullAddress: "Long Phú, Sóc Trăng, Việt Nam",
    shortAddress: "Long Phú",
    maskedAddress: "Long Phú, Sóc Trăng",
    lat: 9.6389,
    lng: 106.0833,
    keywords: ["long phu", "long phú", "sóc trăng", "xe đi long phú"],
  }),
  loc({
    provinceSlug: "soc-trang",
    locationSlug: "tran-de",
    name: "Trần Đề - Sóc Trăng",
    fullAddress: "Trần Đề, Sóc Trăng, Việt Nam",
    shortAddress: "Trần Đề",
    maskedAddress: "Trần Đề, Sóc Trăng",
    lat: 9.5175,
    lng: 106.2036,
    keywords: ["tran de", "trần đề", "sóc trăng", "xe đi trần đề"],
  }),
  loc({
    provinceSlug: "soc-trang",
    locationSlug: "vinh-chau",
    name: "Vĩnh Châu - Sóc Trăng",
    fullAddress: "Vĩnh Châu, Sóc Trăng, Việt Nam",
    shortAddress: "Vĩnh Châu",
    maskedAddress: "Vĩnh Châu, Sóc Trăng",
    lat: 9.3333,
    lng: 105.9833,
    keywords: ["vinh chau", "vĩnh châu", "sóc trăng", "xe đi vĩnh châu"],
  }),
  loc({
    provinceSlug: "soc-trang",
    locationSlug: "nga-nam",
    name: "Ngã Năm - Sóc Trăng",
    fullAddress: "Ngã Năm, Sóc Trăng, Việt Nam",
    shortAddress: "Ngã Năm",
    maskedAddress: "Ngã Năm, Sóc Trăng",
    lat: 9.5667,
    lng: 105.6,
    keywords: ["nga nam", "ngã năm", "sóc trăng", "xe đi ngã năm"],
  }),

  // =========================
  // BẠC LIÊU
  // =========================
  loc({
    provinceSlug: "bac-lieu",
    locationSlug: "bac-lieu",
    name: "Bạc Liêu - Bạc Liêu",
    fullAddress: "Bạc Liêu, Bạc Liêu, Việt Nam",
    shortAddress: "Bạc Liêu",
    maskedAddress: "Bạc Liêu",
    lat: 9.2941,
    lng: 105.7216,
    keywords: ["bac lieu", "bạc liêu", "xe đi bạc liêu"],
  }),
  loc({
    provinceSlug: "bac-lieu",
    locationSlug: "gia-rai",
    name: "Giá Rai - Bạc Liêu",
    fullAddress: "Giá Rai, Bạc Liêu, Việt Nam",
    shortAddress: "Giá Rai",
    maskedAddress: "Giá Rai, Bạc Liêu",
    lat: 9.25,
    lng: 105.45,
    keywords: ["gia rai", "giá rai", "bạc liêu", "xe đi giá rai"],
  }),
  loc({
    provinceSlug: "bac-lieu",
    locationSlug: "hoa-binh",
    name: "Hòa Bình - Bạc Liêu",
    fullAddress: "Hòa Bình, Bạc Liêu, Việt Nam",
    shortAddress: "Hòa Bình",
    maskedAddress: "Hòa Bình, Bạc Liêu",
    lat: 9.2833,
    lng: 105.6167,
    keywords: ["hoa binh", "hòa bình", "bạc liêu", "xe đi hòa bình bạc liêu"],
  }),
  loc({
    provinceSlug: "bac-lieu",
    locationSlug: "dong-hai",
    name: "Đông Hải - Bạc Liêu",
    fullAddress: "Đông Hải, Bạc Liêu, Việt Nam",
    shortAddress: "Đông Hải",
    maskedAddress: "Đông Hải, Bạc Liêu",
    lat: 9.05,
    lng: 105.4167,
    keywords: ["dong hai", "đông hải", "bạc liêu", "xe đi đông hải"],
  }),
  loc({
    provinceSlug: "bac-lieu",
    locationSlug: "phuoc-long",
    name: "Phước Long - Bạc Liêu",
    fullAddress: "Phước Long, Bạc Liêu, Việt Nam",
    shortAddress: "Phước Long",
    maskedAddress: "Phước Long, Bạc Liêu",
    lat: 9.4333,
    lng: 105.4667,
    keywords: [
      "phuoc long",
      "phước long",
      "bạc liêu",
      "xe đi phước long bạc liêu",
    ],
  }),
  loc({
    provinceSlug: "bac-lieu",
    locationSlug: "vinh-loi",
    name: "Vĩnh Lợi - Bạc Liêu",
    fullAddress: "Vĩnh Lợi, Bạc Liêu, Việt Nam",
    shortAddress: "Vĩnh Lợi",
    maskedAddress: "Vĩnh Lợi, Bạc Liêu",
    lat: 9.3333,
    lng: 105.7333,
    keywords: ["vinh loi", "vĩnh lợi", "bạc liêu", "xe đi vĩnh lợi"],
  }),

  // =========================
  // CÀ MAU
  // =========================
  loc({
    provinceSlug: "ca-mau",
    locationSlug: "ca-mau",
    name: "Cà Mau - Cà Mau",
    fullAddress: "Cà Mau, Cà Mau, Việt Nam",
    shortAddress: "Cà Mau",
    maskedAddress: "Cà Mau",
    lat: 9.1769,
    lng: 105.1524,
    keywords: ["ca mau", "cà mau", "xe đi cà mau"],
  }),
  loc({
    provinceSlug: "ca-mau",
    locationSlug: "dat-mui",
    name: "Đất Mũi - Cà Mau",
    fullAddress: "Đất Mũi, Cà Mau, Việt Nam",
    shortAddress: "Đất Mũi",
    maskedAddress: "Đất Mũi, Cà Mau",
    lat: 8.6189,
    lng: 104.7442,
    keywords: ["dat mui", "đất mũi", "cà mau", "xe đi đất mũi"],
  }),
  loc({
    provinceSlug: "ca-mau",
    locationSlug: "nam-can",
    name: "Năm Căn - Cà Mau",
    fullAddress: "Năm Căn, Cà Mau, Việt Nam",
    shortAddress: "Năm Căn",
    maskedAddress: "Năm Căn, Cà Mau",
    lat: 8.8167,
    lng: 104.9833,
    keywords: ["nam can", "năm căn", "cà mau", "xe đi năm căn"],
  }),
  loc({
    provinceSlug: "ca-mau",
    locationSlug: "ngoc-hien",
    name: "Ngọc Hiển - Cà Mau",
    fullAddress: "Ngọc Hiển, Cà Mau, Việt Nam",
    shortAddress: "Ngọc Hiển",
    maskedAddress: "Ngọc Hiển, Cà Mau",
    lat: 8.65,
    lng: 104.9,
    keywords: ["ngoc hien", "ngọc hiển", "cà mau", "xe đi ngọc hiển"],
  }),
  loc({
    provinceSlug: "ca-mau",
    locationSlug: "cai-nuoc",
    name: "Cái Nước - Cà Mau",
    fullAddress: "Cái Nước, Cà Mau, Việt Nam",
    shortAddress: "Cái Nước",
    maskedAddress: "Cái Nước, Cà Mau",
    lat: 8.9431,
    lng: 105.0083,
    keywords: ["cai nuoc", "cái nước", "cà mau", "xe đi cái nước"],
  }),
  loc({
    provinceSlug: "ca-mau",
    locationSlug: "u-minh",
    name: "U Minh - Cà Mau",
    fullAddress: "U Minh, Cà Mau, Việt Nam",
    shortAddress: "U Minh",
    maskedAddress: "U Minh, Cà Mau",
    lat: 9.3833,
    lng: 104.9833,
    keywords: ["u minh", "cà mau", "xe đi u minh"],
  }),
  loc({
    provinceSlug: "ca-mau",
    locationSlug: "tran-van-thoi",
    name: "Trần Văn Thời - Cà Mau",
    fullAddress: "Trần Văn Thời, Cà Mau, Việt Nam",
    shortAddress: "Trần Văn Thời",
    maskedAddress: "Trần Văn Thời, Cà Mau",
    lat: 9.0833,
    lng: 104.9833,
    keywords: [
      "tran van thoi",
      "trần văn thời",
      "cà mau",
      "xe đi trần văn thời",
    ],
  }),

  // =========================
  // CẦN THƠ
  // =========================
  loc({
    provinceSlug: "can-tho",
    locationSlug: "ninh-kieu",
    name: "Ninh Kiều - Cần Thơ",
    fullAddress: "Ninh Kiều, Cần Thơ, Việt Nam",
    shortAddress: "Ninh Kiều",
    maskedAddress: "Ninh Kiều, Cần Thơ",
    lat: 10.0342,
    lng: 105.7883,
    keywords: [
      "ninh kieu",
      "ninh kiều",
      "can tho",
      "cần thơ",
      "xe đi ninh kiều",
      "xe đi cần thơ",
    ],
  }),
  loc({
    provinceSlug: "can-tho",
    locationSlug: "binh-thuy",
    name: "Bình Thủy - Cần Thơ",
    fullAddress: "Bình Thủy, Cần Thơ, Việt Nam",
    shortAddress: "Bình Thủy",
    maskedAddress: "Bình Thủy, Cần Thơ",
    lat: 10.0742,
    lng: 105.7408,
    keywords: [
      "binh thuy",
      "bình thủy",
      "can tho",
      "cần thơ",
      "xe đi bình thủy",
    ],
  }),
  loc({
    provinceSlug: "can-tho",
    locationSlug: "cai-rang",
    name: "Cái Răng - Cần Thơ",
    fullAddress: "Cái Răng, Cần Thơ, Việt Nam",
    shortAddress: "Cái Răng",
    maskedAddress: "Cái Răng, Cần Thơ",
    lat: 10.0,
    lng: 105.8,
    keywords: ["cai rang", "cái răng", "can tho", "cần thơ", "xe đi cái răng"],
  }),
  loc({
    provinceSlug: "can-tho",
    locationSlug: "o-mon",
    name: "Ô Môn - Cần Thơ",
    fullAddress: "Ô Môn, Cần Thơ, Việt Nam",
    shortAddress: "Ô Môn",
    maskedAddress: "Ô Môn, Cần Thơ",
    lat: 10.117,
    lng: 105.63,
    keywords: ["o mon", "ô môn", "can tho", "cần thơ", "xe đi ô môn"],
  }),
  loc({
    provinceSlug: "can-tho",
    locationSlug: "thot-not",
    name: "Thốt Nốt - Cần Thơ",
    fullAddress: "Thốt Nốt, Cần Thơ, Việt Nam",
    shortAddress: "Thốt Nốt",
    maskedAddress: "Thốt Nốt, Cần Thơ",
    lat: 10.2725,
    lng: 105.5336,
    keywords: ["thot not", "thốt nốt", "can tho", "cần thơ", "xe đi thốt nốt"],
  }),
  loc({
    provinceSlug: "can-tho",
    locationSlug: "phong-dien",
    name: "Phong Điền - Cần Thơ",
    fullAddress: "Phong Điền, Cần Thơ, Việt Nam",
    shortAddress: "Phong Điền",
    maskedAddress: "Phong Điền, Cần Thơ",
    lat: 9.995,
    lng: 105.6667,
    keywords: [
      "phong dien",
      "phong điền",
      "can tho",
      "cần thơ",
      "xe đi phong điền",
    ],
  }),
  loc({
    provinceSlug: "can-tho",
    locationSlug: "co-do",
    name: "Cờ Đỏ - Cần Thơ",
    fullAddress: "Cờ Đỏ, Cần Thơ, Việt Nam",
    shortAddress: "Cờ Đỏ",
    maskedAddress: "Cờ Đỏ, Cần Thơ",
    lat: 10.095,
    lng: 105.43,
    keywords: ["co do", "cờ đỏ", "can tho", "cần thơ", "xe đi cờ đỏ"],
  }),
  loc({
    provinceSlug: "can-tho",
    locationSlug: "vinh-thanh",
    name: "Vĩnh Thạnh - Cần Thơ",
    fullAddress: "Vĩnh Thạnh, Cần Thơ, Việt Nam",
    shortAddress: "Vĩnh Thạnh",
    maskedAddress: "Vĩnh Thạnh, Cần Thơ",
    lat: 10.2225,
    lng: 105.3986,
    keywords: [
      "vinh thanh",
      "vĩnh thạnh",
      "can tho",
      "cần thơ",
      "xe đi vĩnh thạnh cần thơ",
    ],
  }),

  // =========================
  // ĐIỂM DU LỊCH SEO MẠNH
  // =========================
  loc({
    provinceSlug: "ca-mau",
    locationSlug: "mui-ca-mau",
    name: "Mũi Cà Mau",
    fullAddress: "Mũi Cà Mau, Cà Mau, Việt Nam",
    shortAddress: "Mũi Cà Mau",
    maskedAddress: "Mũi Cà Mau",
    lat: 8.6081,
    lng: 104.7328,
    keywords: ["mui ca mau", "mũi cà mau", "xe đi mũi cà mau"],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "nam-du",
    name: "Nam Du",
    fullAddress: "Nam Du, Kiên Giang, Việt Nam",
    shortAddress: "Nam Du",
    maskedAddress: "Nam Du, Kiên Giang",
    lat: 9.6833,
    lng: 104.35,
    keywords: ["nam du", "xe đi nam du"],
  }),
  loc({
    provinceSlug: "kien-giang",
    locationSlug: "hon-son",
    name: "Hòn Sơn",
    fullAddress: "Hòn Sơn, Kiên Giang, Việt Nam",
    shortAddress: "Hòn Sơn",
    maskedAddress: "Hòn Sơn, Kiên Giang",
    lat: 9.81,
    lng: 104.63,
    keywords: ["hon son", "hòn sơn", "xe đi hòn sơn"],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "nui-sam",
    name: "Núi Sam",
    fullAddress: "Núi Sam, An Giang, Việt Nam",
    shortAddress: "Núi Sam",
    maskedAddress: "Núi Sam, An Giang",
    lat: 10.6811,
    lng: 105.0808,
    keywords: ["nui sam", "núi sam", "xe đi núi sam"],
  }),
  loc({
    provinceSlug: "an-giang",
    locationSlug: "mieu-ba-chua-xu",
    name: "Miếu Bà Chúa Xứ",
    fullAddress: "Miếu Bà Chúa Xứ, Châu Đốc, An Giang, Việt Nam",
    shortAddress: "Miếu Bà Chúa Xứ",
    maskedAddress: "Châu Đốc, An Giang",
    lat: 10.6823,
    lng: 105.0802,
    keywords: ["mieu ba chua xu", "miếu bà chúa xứ", "xe đi miếu bà chúa xứ"],
  }),
  // =========================
  // MEKONG PHASE 2 - BẾN TÀU / DU LỊCH / KCN
  // =========================

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "ben-tau-rach-gia",
    name: "Bến tàu Rạch Giá",
    fullAddress: "Bến tàu Rạch Giá, Rạch Giá, Kiên Giang, Việt Nam",
    shortAddress: "Bến tàu Rạch Giá",
    maskedAddress: "Rạch Giá, Kiên Giang",
    lat: 10.0116,
    lng: 105.0819,
    keywords: [
      "ben tau rach gia",
      "bến tàu rạch giá",
      "tàu đi phú quốc",
      "tàu đi nam du",
      "xe đi bến tàu rạch giá",
    ],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "ben-tau-ha-tien",
    name: "Bến tàu Hà Tiên",
    fullAddress: "Bến tàu Hà Tiên, Hà Tiên, Kiên Giang, Việt Nam",
    shortAddress: "Bến tàu Hà Tiên",
    maskedAddress: "Hà Tiên, Kiên Giang",
    lat: 10.3828,
    lng: 104.4876,
    keywords: [
      "ben tau ha tien",
      "bến tàu hà tiên",
      "tàu đi phú quốc",
      "xe đi bến tàu hà tiên",
    ],
  }),

  loc({
    provinceSlug: "soc-trang",
    locationSlug: "ben-tau-tran-de",
    name: "Bến tàu Trần Đề",
    fullAddress: "Bến tàu Trần Đề, Sóc Trăng, Việt Nam",
    shortAddress: "Bến tàu Trần Đề",
    maskedAddress: "Trần Đề, Sóc Trăng",
    lat: 9.5139,
    lng: 106.2036,
    keywords: [
      "ben tau tran de",
      "bến tàu trần đề",
      "tàu đi côn đảo",
      "xe đi bến tàu trần đề",
    ],
  }),

  loc({
    provinceSlug: "can-tho",
    locationSlug: "cho-noi-cai-rang",
    name: "Chợ nổi Cái Răng",
    fullAddress: "Chợ nổi Cái Răng, Cần Thơ, Việt Nam",
    shortAddress: "Chợ nổi Cái Răng",
    maskedAddress: "Cái Răng, Cần Thơ",
    lat: 10.0068,
    lng: 105.775,
    keywords: [
      "cho noi cai rang",
      "chợ nổi cái răng",
      "cần thơ",
      "xe đi chợ nổi cái răng",
    ],
  }),

  loc({
    provinceSlug: "tien-giang",
    locationSlug: "cho-noi-cai-be",
    name: "Chợ nổi Cái Bè",
    fullAddress: "Chợ nổi Cái Bè, Tiền Giang, Việt Nam",
    shortAddress: "Chợ nổi Cái Bè",
    maskedAddress: "Cái Bè, Tiền Giang",
    lat: 10.3342,
    lng: 106.0308,
    keywords: [
      "cho noi cai be",
      "chợ nổi cái bè",
      "cái bè",
      "xe đi chợ nổi cái bè",
    ],
  }),

  loc({
    provinceSlug: "dong-thap",
    locationSlug: "tram-chim",
    name: "Vườn quốc gia Tràm Chim",
    fullAddress: "Vườn quốc gia Tràm Chim, Tam Nông, Đồng Tháp, Việt Nam",
    shortAddress: "Tràm Chim",
    maskedAddress: "Tam Nông, Đồng Tháp",
    lat: 10.7108,
    lng: 105.5158,
    keywords: [
      "tram chim",
      "tràm chim",
      "vườn quốc gia tràm chim",
      "xe đi tràm chim",
    ],
  }),

  loc({
    provinceSlug: "dong-thap",
    locationSlug: "gao-giong",
    name: "Khu du lịch Gáo Giồng",
    fullAddress: "Khu du lịch Gáo Giồng, Cao Lãnh, Đồng Tháp, Việt Nam",
    shortAddress: "Gáo Giồng",
    maskedAddress: "Cao Lãnh, Đồng Tháp",
    lat: 10.5139,
    lng: 105.6667,
    keywords: [
      "gao giong",
      "gáo giồng",
      "khu du lịch gáo giồng",
      "xe đi gáo giồng",
    ],
  }),

  loc({
    provinceSlug: "an-giang",
    locationSlug: "nui-cam",
    name: "Núi Cấm",
    fullAddress: "Núi Cấm, Tịnh Biên, An Giang, Việt Nam",
    shortAddress: "Núi Cấm",
    maskedAddress: "Tịnh Biên, An Giang",
    lat: 10.4964,
    lng: 104.9908,
    keywords: ["nui cam", "núi cấm", "thất sơn", "an giang", "xe đi núi cấm"],
  }),

  loc({
    provinceSlug: "an-giang",
    locationSlug: "ba-chuc",
    name: "Ba Chúc",
    fullAddress: "Ba Chúc, Tri Tôn, An Giang, Việt Nam",
    shortAddress: "Ba Chúc",
    maskedAddress: "Tri Tôn, An Giang",
    lat: 10.4072,
    lng: 104.9275,
    keywords: ["ba chuc", "ba chúc", "tri tôn", "an giang", "xe đi ba chúc"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "mui-nai",
    name: "Mũi Nai",
    fullAddress: "Mũi Nai, Hà Tiên, Kiên Giang, Việt Nam",
    shortAddress: "Mũi Nai",
    maskedAddress: "Hà Tiên, Kiên Giang",
    lat: 10.3794,
    lng: 104.4436,
    keywords: ["mui nai", "mũi nai", "hà tiên", "xe đi mũi nai"],
  }),
    // =========================
  // MEKONG PHASE 2B - KHU CÔNG NGHIỆP / ĐIỂM DU LỊCH THÊM
  // =========================

  loc({
    provinceSlug: "long-an",
    locationSlug: "kcn-long-hau",
    name: "KCN Long Hậu",
    fullAddress: "KCN Long Hậu, Cần Giuộc, Long An, Việt Nam",
    shortAddress: "KCN Long Hậu",
    maskedAddress: "Cần Giuộc, Long An",
    lat: 10.6475,
    lng: 106.7375,
    keywords: ["kcn long hau", "kcn long hậu", "long hậu", "xe đi kcn long hậu"],
  }),

  loc({
    provinceSlug: "long-an",
    locationSlug: "kcn-tan-duc",
    name: "KCN Tân Đức",
    fullAddress: "KCN Tân Đức, Đức Hòa, Long An, Việt Nam",
    shortAddress: "KCN Tân Đức",
    maskedAddress: "Đức Hòa, Long An",
    lat: 10.8575,
    lng: 106.4025,
    keywords: ["kcn tan duc", "kcn tân đức", "tân đức", "xe đi kcn tân đức"],
  }),

  loc({
    provinceSlug: "long-an",
    locationSlug: "kcn-thuan-dao",
    name: "KCN Thuận Đạo",
    fullAddress: "KCN Thuận Đạo, Bến Lức, Long An, Việt Nam",
    shortAddress: "KCN Thuận Đạo",
    maskedAddress: "Bến Lức, Long An",
    lat: 10.6575,
    lng: 106.4925,
    keywords: ["kcn thuan dao", "kcn thuận đạo", "thuận đạo", "xe đi kcn thuận đạo"],
  }),

  loc({
    provinceSlug: "tien-giang",
    locationSlug: "kcn-tan-huong",
    name: "KCN Tân Hương",
    fullAddress: "KCN Tân Hương, Châu Thành, Tiền Giang, Việt Nam",
    shortAddress: "KCN Tân Hương",
    maskedAddress: "Châu Thành, Tiền Giang",
    lat: 10.4075,
    lng: 106.2445,
    keywords: ["kcn tan huong", "kcn tân hương", "tân hương", "xe đi kcn tân hương"],
  }),

  loc({
    provinceSlug: "tien-giang",
    locationSlug: "kcn-long-giang",
    name: "KCN Long Giang",
    fullAddress: "KCN Long Giang, Tân Phước, Tiền Giang, Việt Nam",
    shortAddress: "KCN Long Giang",
    maskedAddress: "Tân Phước, Tiền Giang",
    lat: 10.4635,
    lng: 106.2705,
    keywords: ["kcn long giang", "long giang", "tiền giang", "xe đi kcn long giang"],
  }),

  loc({
    provinceSlug: "vinh-long",
    locationSlug: "kcn-hoa-phu",
    name: "KCN Hòa Phú",
    fullAddress: "KCN Hòa Phú, Long Hồ, Vĩnh Long, Việt Nam",
    shortAddress: "KCN Hòa Phú",
    maskedAddress: "Long Hồ, Vĩnh Long",
    lat: 10.2065,
    lng: 105.9325,
    keywords: ["kcn hoa phu", "kcn hòa phú", "hòa phú vĩnh long", "xe đi kcn hòa phú"],
  }),

  loc({
    provinceSlug: "can-tho",
    locationSlug: "kcn-tra-noc",
    name: "KCN Trà Nóc",
    fullAddress: "KCN Trà Nóc, Bình Thủy, Cần Thơ, Việt Nam",
    shortAddress: "KCN Trà Nóc",
    maskedAddress: "Bình Thủy, Cần Thơ",
    lat: 10.0965,
    lng: 105.7225,
    keywords: ["kcn tra noc", "kcn trà nóc", "trà nóc", "xe đi kcn trà nóc"],
  }),

  loc({
    provinceSlug: "hau-giang",
    locationSlug: "kcn-song-hau",
    name: "KCN Sông Hậu",
    fullAddress: "KCN Sông Hậu, Châu Thành, Hậu Giang, Việt Nam",
    shortAddress: "KCN Sông Hậu",
    maskedAddress: "Châu Thành, Hậu Giang",
    lat: 9.9355,
    lng: 105.8235,
    keywords: ["kcn song hau", "kcn sông hậu", "sông hậu", "xe đi kcn sông hậu"],
  }),

  loc({
    provinceSlug: "soc-trang",
    locationSlug: "kcn-an-nghiep",
    name: "KCN An Nghiệp",
    fullAddress: "KCN An Nghiệp, Sóc Trăng, Việt Nam",
    shortAddress: "KCN An Nghiệp",
    maskedAddress: "Sóc Trăng",
    lat: 9.6405,
    lng: 105.9515,
    keywords: ["kcn an nghiep", "kcn an nghiệp", "an nghiệp sóc trăng", "xe đi kcn an nghiệp"],
  }),

  loc({
    provinceSlug: "ben-tre",
    locationSlug: "con-phung",
    name: "Cồn Phụng",
    fullAddress: "Cồn Phụng, Châu Thành, Bến Tre, Việt Nam",
    shortAddress: "Cồn Phụng",
    maskedAddress: "Châu Thành, Bến Tre",
    lat: 10.3235,
    lng: 106.3385,
    keywords: ["con phung", "cồn phụng", "bến tre", "xe đi cồn phụng"],
  }),

  loc({
    provinceSlug: "can-tho",
    locationSlug: "con-son",
    name: "Cồn Sơn",
    fullAddress: "Cồn Sơn, Bình Thủy, Cần Thơ, Việt Nam",
    shortAddress: "Cồn Sơn",
    maskedAddress: "Bình Thủy, Cần Thơ",
    lat: 10.0655,
    lng: 105.7555,
    keywords: ["con son", "cồn sơn", "cần thơ", "xe đi cồn sơn"],
  }),

  loc({
    provinceSlug: "can-tho",
    locationSlug: "ben-ninh-kieu",
    name: "Bến Ninh Kiều",
    fullAddress: "Bến Ninh Kiều, Ninh Kiều, Cần Thơ, Việt Nam",
    shortAddress: "Bến Ninh Kiều",
    maskedAddress: "Ninh Kiều, Cần Thơ",
    lat: 10.0335,
    lng: 105.7885,
    keywords: ["ben ninh kieu", "bến ninh kiều", "ninh kiều", "xe đi bến ninh kiều"],
  }),

  loc({
    provinceSlug: "ca-mau",
    locationSlug: "cho-noi-ca-mau",
    name: "Chợ nổi Cà Mau",
    fullAddress: "Chợ nổi Cà Mau, Cà Mau, Việt Nam",
    shortAddress: "Chợ nổi Cà Mau",
    maskedAddress: "Cà Mau",
    lat: 9.1805,
    lng: 105.1525,
    keywords: ["cho noi ca mau", "chợ nổi cà mau", "cà mau", "xe đi chợ nổi cà mau"],
  }),

  loc({
    provinceSlug: "bac-lieu",
    locationSlug: "nha-cong-tu-bac-lieu",
    name: "Nhà Công tử Bạc Liêu",
    fullAddress: "Nhà Công tử Bạc Liêu, Bạc Liêu, Việt Nam",
    shortAddress: "Nhà Công tử Bạc Liêu",
    maskedAddress: "Bạc Liêu",
    lat: 9.2875,
    lng: 105.7245,
    keywords: ["nha cong tu bac lieu", "nhà công tử bạc liêu", "bạc liêu", "xe đi nhà công tử bạc liêu"],
  }),

  loc({
    provinceSlug: "bac-lieu",
    locationSlug: "dien-gio-bac-lieu",
    name: "Cánh đồng điện gió Bạc Liêu",
    fullAddress: "Cánh đồng điện gió Bạc Liêu, Bạc Liêu, Việt Nam",
    shortAddress: "Điện gió Bạc Liêu",
    maskedAddress: "Bạc Liêu",
    lat: 9.2265,
    lng: 105.8065,
    keywords: ["dien gio bac lieu", "điện gió bạc liêu", "cánh đồng điện gió", "xe đi điện gió bạc liêu"],
  }),
    // =========================
  // MEKONG PHASE 2C - BIỂN ĐẢO TÂY NAM
  // =========================

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "cang-hanh-khach-rach-gia",
    name: "Cảng hành khách Rạch Giá",
    fullAddress: "Cảng hành khách Rạch Giá, Kiên Giang, Việt Nam",
    shortAddress: "Cảng Rạch Giá",
    maskedAddress: "Rạch Giá, Kiên Giang",
    lat: 10.0152,
    lng: 105.0823,
    keywords: ["cang rach gia", "cảng rạch giá", "tàu phú quốc", "tàu nam du", "xe đi cảng rạch giá"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "cang-hanh-khach-ha-tien",
    name: "Cảng hành khách Hà Tiên",
    fullAddress: "Cảng hành khách Hà Tiên, Kiên Giang, Việt Nam",
    shortAddress: "Cảng Hà Tiên",
    maskedAddress: "Hà Tiên, Kiên Giang",
    lat: 10.3835,
    lng: 104.4870,
    keywords: ["cang ha tien", "cảng hà tiên", "tàu phú quốc", "xe đi cảng hà tiên"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "duong-dong",
    name: "Dương Đông - Phú Quốc",
    fullAddress: "Dương Đông, Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "Dương Đông",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.2192,
    lng: 103.9608,
    keywords: ["duong dong", "dương đông", "phú quốc", "xe đi dương đông"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "an-thoi",
    name: "An Thới - Phú Quốc",
    fullAddress: "An Thới, Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "An Thới",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.0450,
    lng: 104.0150,
    keywords: ["an thoi", "an thới", "phú quốc", "xe đi an thới"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "bai-sao",
    name: "Bãi Sao",
    fullAddress: "Bãi Sao, Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "Bãi Sao",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.0353,
    lng: 104.0353,
    keywords: ["bai sao", "bãi sao", "phú quốc", "xe đi bãi sao"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "grand-world-phu-quoc",
    name: "Grand World Phú Quốc",
    fullAddress: "Grand World Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "Grand World",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.3385,
    lng: 103.8555,
    keywords: ["grand world", "grand world phú quốc", "xe đi grand world"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "vinwonders-phu-quoc",
    name: "VinWonders Phú Quốc",
    fullAddress: "VinWonders Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "VinWonders",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.3370,
    lng: 103.8510,
    keywords: ["vinwonders", "vinwonders phú quốc", "xe đi vinwonders"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "sunset-town",
    name: "Sunset Town",
    fullAddress: "Sunset Town, Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "Sunset Town",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.0295,
    lng: 104.0028,
    keywords: ["sunset town", "thị trấn hoàng hôn", "phú quốc", "xe đi sunset town"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "hon-thom",
    name: "Hòn Thơm",
    fullAddress: "Hòn Thơm, Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "Hòn Thơm",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 9.9800,
    lng: 104.0300,
    keywords: ["hon thom", "hòn thơm", "cáp treo hòn thơm", "xe đi hòn thơm"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "dao-nam-du",
    name: "Đảo Nam Du",
    fullAddress: "Nam Du, Kiên Giang, Việt Nam",
    shortAddress: "Nam Du",
    maskedAddress: "Kiên Giang",
    lat: 9.6900,
    lng: 104.3500,
    keywords: ["nam du", "đảo nam du", "xe đi nam du"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "dao-hon-son",
    name: "Đảo Hòn Sơn",
    fullAddress: "Hòn Sơn, Kiên Giang, Việt Nam",
    shortAddress: "Hòn Sơn",
    maskedAddress: "Kiên Giang",
    lat: 9.8200,
    lng: 104.6200,
    keywords: ["hon son", "hòn sơn", "xe đi hòn sơn"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "lang-chai-ham-ninh",
    name: "Làng chài Hàm Ninh",
    fullAddress: "Hàm Ninh, Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "Hàm Ninh",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.1783,
    lng: 104.0503,
    keywords: ["ham ninh", "hàm ninh", "làng chài hàm ninh", "xe đi hàm ninh"],
  }),
    // =========================
  // MEKONG PHASE 3 - SÂN BAY MIỀN TÂY
  // =========================

  loc({
    provinceSlug: "can-tho",
    locationSlug: "san-bay-can-tho",
    name: "Sân bay Cần Thơ",
    fullAddress: "Sân bay quốc tế Cần Thơ, Bình Thủy, Cần Thơ, Việt Nam",
    shortAddress: "Sân bay Cần Thơ",
    maskedAddress: "Bình Thủy, Cần Thơ",
    lat: 10.0851,
    lng: 105.7119,
    keywords: ["san bay can tho", "sân bay cần thơ", "sân bay quốc tế cần thơ", "xe đi sân bay cần thơ"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "san-bay-phu-quoc",
    name: "Sân bay Phú Quốc",
    fullAddress: "Sân bay quốc tế Phú Quốc, Phú Quốc, Kiên Giang, Việt Nam",
    shortAddress: "Sân bay Phú Quốc",
    maskedAddress: "Phú Quốc, Kiên Giang",
    lat: 10.1698,
    lng: 103.9931,
    keywords: ["san bay phu quoc", "sân bay phú quốc", "sân bay quốc tế phú quốc", "xe đi sân bay phú quốc"],
  }),

  loc({
    provinceSlug: "kien-giang",
    locationSlug: "san-bay-rach-gia",
    name: "Sân bay Rạch Giá",
    fullAddress: "Sân bay Rạch Giá, Rạch Giá, Kiên Giang, Việt Nam",
    shortAddress: "Sân bay Rạch Giá",
    maskedAddress: "Rạch Giá, Kiên Giang",
    lat: 9.9580,
    lng: 105.1324,
    keywords: ["san bay rach gia", "sân bay rạch giá", "xe đi sân bay rạch giá"],
  }),

  loc({
    provinceSlug: "ca-mau",
    locationSlug: "san-bay-ca-mau",
    name: "Sân bay Cà Mau",
    fullAddress: "Sân bay Cà Mau, Cà Mau, Việt Nam",
    shortAddress: "Sân bay Cà Mau",
    maskedAddress: "Cà Mau",
    lat: 9.1777,
    lng: 105.1778,
    keywords: ["san bay ca mau", "sân bay cà mau", "xe đi sân bay cà mau"],
  }),
];
