// apps/rider-mobile/constants/provinces.js

const province = ({
  provinceSlug,
  name,
  fullAddress,
  shortAddress,
  maskedAddress,
  lat,
  lng,
  keywords,
}) => ({
  placeId: `goviet247:province:${provinceSlug}`,
  name,
  fullAddress,
  shortAddress,
  maskedAddress,
  lat,
  lng,
  keywords,
});

export const PROVINCES = [
    // =========================
  // BLOCK A - MIỀN BẮC
  // =========================

  province({
    provinceSlug: "ha-noi",
    name: "Hà Nội",
    fullAddress: "Hà Nội, Việt Nam",
    shortAddress: "Hà Nội",
    maskedAddress: "Hà Nội",
    lat: 21.0285,
    lng: 105.8542,
    keywords: ["ha noi", "hà nội", "thu do", "thủ đô", "xe đi hà nội"],
  }),

  province({
    provinceSlug: "tuyen-quang",
    name: "Tuyên Quang",
    fullAddress: "Tuyên Quang, Việt Nam",
    shortAddress: "Tuyên Quang",
    maskedAddress: "Tuyên Quang",
    lat: 21.8233,
    lng: 105.2181,
    keywords: ["tuyen quang", "tuyên quang", "ha giang", "hà giang", "xe đi tuyên quang", "xe đi hà giang"],
  }),

  province({
    provinceSlug: "lao-cai",
    name: "Lào Cai",
    fullAddress: "Lào Cai, Việt Nam",
    shortAddress: "Lào Cai",
    maskedAddress: "Lào Cai",
    lat: 22.4856,
    lng: 103.9707,
    keywords: ["lao cai", "lào cai", "yen bai", "yên bái", "sapa", "sa pa", "xe đi lào cai", "xe đi sapa"],
  }),

  province({
    provinceSlug: "thai-nguyen",
    name: "Thái Nguyên",
    fullAddress: "Thái Nguyên, Việt Nam",
    shortAddress: "Thái Nguyên",
    maskedAddress: "Thái Nguyên",
    lat: 21.5942,
    lng: 105.8482,
    keywords: ["thai nguyen", "thái nguyên", "bac kan", "bắc kạn", "xe đi thái nguyên"],
  }),

  province({
    provinceSlug: "phu-tho",
    name: "Phú Thọ",
    fullAddress: "Phú Thọ, Việt Nam",
    shortAddress: "Phú Thọ",
    maskedAddress: "Phú Thọ",
    lat: 21.3227,
    lng: 105.4018,
    keywords: ["phu tho", "phú thọ", "viet tri", "việt trì", "vinh phuc", "vĩnh phúc", "hoa binh", "hòa bình", "xe đi phú thọ"],
  }),

  province({
    provinceSlug: "bac-ninh",
    name: "Bắc Ninh",
    fullAddress: "Bắc Ninh, Việt Nam",
    shortAddress: "Bắc Ninh",
    maskedAddress: "Bắc Ninh",
    lat: 21.1861,
    lng: 106.0763,
    keywords: ["bac ninh", "bắc ninh", "bac giang", "bắc giang", "que vo", "quế võ", "yên phong", "xe đi bắc ninh"],
  }),

  province({
    provinceSlug: "hung-yen",
    name: "Hưng Yên",
    fullAddress: "Hưng Yên, Việt Nam",
    shortAddress: "Hưng Yên",
    maskedAddress: "Hưng Yên",
    lat: 20.8526,
    lng: 106.0160,
    keywords: ["hung yen", "hưng yên", "thai binh", "thái bình", "pho hien", "phố hiến", "xe đi hưng yên"],
  }),

  province({
    provinceSlug: "hai-phong",
    name: "Hải Phòng",
    fullAddress: "Hải Phòng, Việt Nam",
    shortAddress: "Hải Phòng",
    maskedAddress: "Hải Phòng",
    lat: 20.8449,
    lng: 106.6881,
    keywords: ["hai phong", "hải phòng", "hai duong", "hải dương", "cat bi", "cát bi", "do son", "đồ sơn", "xe đi hải phòng"],
  }),

  province({
    provinceSlug: "ninh-binh",
    name: "Ninh Bình",
    fullAddress: "Ninh Bình, Việt Nam",
    shortAddress: "Ninh Bình",
    maskedAddress: "Ninh Bình",
    lat: 20.2506,
    lng: 105.9745,
    keywords: ["ninh binh", "ninh bình", "nam dinh", "nam định", "ha nam", "hà nam", "trang an", "tràng an", "tam coc", "tam cốc", "xe đi ninh bình"],
  }),

  province({
    provinceSlug: "quang-ninh",
    name: "Quảng Ninh",
    fullAddress: "Quảng Ninh, Việt Nam",
    shortAddress: "Quảng Ninh",
    maskedAddress: "Quảng Ninh",
    lat: 20.9712,
    lng: 107.0448,
    keywords: ["quang ninh", "quảng ninh", "ha long", "hạ long", "van don", "vân đồn", "mong cai", "móng cái", "xe đi quảng ninh"],
  }),

  province({
    provinceSlug: "cao-bang",
    name: "Cao Bằng",
    fullAddress: "Cao Bằng, Việt Nam",
    shortAddress: "Cao Bằng",
    maskedAddress: "Cao Bằng",
    lat: 22.6666,
    lng: 106.2639,
    keywords: ["cao bang", "cao bằng", "ban gioc", "bản giốc", "xe đi cao bằng"],
  }),

  province({
    provinceSlug: "lang-son",
    name: "Lạng Sơn",
    fullAddress: "Lạng Sơn, Việt Nam",
    shortAddress: "Lạng Sơn",
    maskedAddress: "Lạng Sơn",
    lat: 21.8537,
    lng: 106.7615,
    keywords: ["lang son", "lạng sơn", "dong dang", "đồng đăng", "mau son", "mẫu sơn", "xe đi lạng sơn"],
  }),

  province({
    provinceSlug: "lai-chau",
    name: "Lai Châu",
    fullAddress: "Lai Châu, Việt Nam",
    shortAddress: "Lai Châu",
    maskedAddress: "Lai Châu",
    lat: 22.3862,
    lng: 103.4707,
    keywords: ["lai chau", "lai châu", "tam duong", "tam đường", "xe đi lai châu"],
  }),

  province({
    provinceSlug: "dien-bien",
    name: "Điện Biên",
    fullAddress: "Điện Biên, Việt Nam",
    shortAddress: "Điện Biên",
    maskedAddress: "Điện Biên",
    lat: 21.3860,
    lng: 103.0230,
    keywords: ["dien bien", "điện biên", "dien bien phu", "điện biên phủ", "xe đi điện biên"],
  }),

  province({
    provinceSlug: "son-la",
    name: "Sơn La",
    fullAddress: "Sơn La, Việt Nam",
    shortAddress: "Sơn La",
    maskedAddress: "Sơn La",
    lat: 21.3270,
    lng: 103.9141,
    keywords: ["son la", "sơn la", "moc chau", "mộc châu", "xe đi sơn la", "xe đi mộc châu"],
  }),

  province({
    provinceSlug: "thanh-hoa",
    name: "Thanh Hóa",
    fullAddress: "Thanh Hóa, Việt Nam",
    shortAddress: "Thanh Hóa",
    maskedAddress: "Thanh Hóa",
    lat: 19.8077,
    lng: 105.7764,
    keywords: ["thanh hoa", "thanh hóa", "sam son", "sầm sơn", "tho xuan", "thọ xuân", "xe đi thanh hóa"],
  }),
    // =========================
  // BLOCK B - MIỀN TRUNG + TÂY NGUYÊN
  // =========================

  province({
    provinceSlug: "nghe-an",
    name: "Nghệ An",
    fullAddress: "Nghệ An, Việt Nam",
    shortAddress: "Nghệ An",
    maskedAddress: "Nghệ An",
    lat: 18.6734,
    lng: 105.6922,
    keywords: [
      "nghe an",
      "nghệ an",
      "vinh",
      "cua lo",
      "cửa lò",
      "xe đi nghệ an",
    ],
  }),

  province({
    provinceSlug: "ha-tinh",
    name: "Hà Tĩnh",
    fullAddress: "Hà Tĩnh, Việt Nam",
    shortAddress: "Hà Tĩnh",
    maskedAddress: "Hà Tĩnh",
    lat: 18.3559,
    lng: 105.8877,
    keywords: [
      "ha tinh",
      "hà tĩnh",
      "ky anh",
      "kỳ anh",
      "xe đi hà tĩnh",
    ],
  }),

  province({
    provinceSlug: "quang-tri",
    name: "Quảng Trị",
    fullAddress: "Quảng Trị, Việt Nam",
    shortAddress: "Quảng Trị",
    maskedAddress: "Quảng Trị",
    lat: 16.7500,
    lng: 107.2000,
    keywords: [
      "quang tri",
      "quảng trị",
      "dong ha",
      "đông hà",
      "xe đi quảng trị",
    ],
  }),

  province({
    provinceSlug: "hue",
    name: "Huế",
    fullAddress: "Huế, Việt Nam",
    shortAddress: "Huế",
    maskedAddress: "Huế",
    lat: 16.4637,
    lng: 107.5909,
    keywords: [
      "hue",
      "huế",
      "co do",
      "cố đô",
      "lang co",
      "lăng cô",
      "xe đi huế",
    ],
  }),

  province({
    provinceSlug: "da-nang",
    name: "Đà Nẵng",
    fullAddress: "Đà Nẵng, Việt Nam",
    shortAddress: "Đà Nẵng",
    maskedAddress: "Đà Nẵng",
    lat: 16.0544,
    lng: 108.2022,
    keywords: [
      "da nang",
      "đà nẵng",
      "my khe",
      "mỹ khê",
      "son tra",
      "sơn trà",
      "xe đi đà nẵng",
    ],
  }),

  province({
    provinceSlug: "quang-ngai",
    name: "Quảng Ngãi",
    fullAddress: "Quảng Ngãi, Việt Nam",
    shortAddress: "Quảng Ngãi",
    maskedAddress: "Quảng Ngãi",
    lat: 15.1214,
    lng: 108.8044,
    keywords: [
      "quang ngai",
      "quảng ngãi",
      "ly son",
      "lý sơn",
      "xe đi quảng ngãi",
    ],
  }),

  province({
    provinceSlug: "gia-lai",
    name: "Gia Lai",
    fullAddress: "Gia Lai, Việt Nam",
    shortAddress: "Gia Lai",
    maskedAddress: "Gia Lai",
    lat: 13.9833,
    lng: 108.0000,
    keywords: [
      "gia lai",
      "pleiku",
      "biển hồ",
      "bien ho",
      "xe đi gia lai",
    ],
  }),

  province({
    provinceSlug: "dak-lak",
    name: "Đắk Lắk",
    fullAddress: "Đắk Lắk, Việt Nam",
    shortAddress: "Đắk Lắk",
    maskedAddress: "Đắk Lắk",
    lat: 12.7100,
    lng: 108.2378,
    keywords: [
      "dak lak",
      "đắk lắk",
      "buon ma thuot",
      "buôn ma thuột",
      "xe đi đắk lắk",
    ],
  }),

  province({
    provinceSlug: "khanh-hoa",
    name: "Khánh Hòa",
    fullAddress: "Khánh Hòa, Việt Nam",
    shortAddress: "Khánh Hòa",
    maskedAddress: "Khánh Hòa",
    lat: 12.2388,
    lng: 109.1967,
    keywords: [
      "khanh hoa",
      "khánh hòa",
      "nha trang",
      "cam ranh",
      "xe đi nha trang",
      "xe đi khánh hòa",
    ],
  }),

  province({
    provinceSlug: "lam-dong",
    name: "Lâm Đồng",
    fullAddress: "Lâm Đồng, Việt Nam",
    shortAddress: "Lâm Đồng",
    maskedAddress: "Lâm Đồng",
    lat: 11.9404,
    lng: 108.4583,
    keywords: [
      "lam dong",
      "lâm đồng",
      "da lat",
      "đà lạt",
      "bao loc",
      "bảo lộc",
      "xe đi lâm đồng",
    ],
  }),

  province({
    provinceSlug: "dak-nong",
    name: "Đắk Nông",
    fullAddress: "Đắk Nông, Việt Nam",
    shortAddress: "Đắk Nông",
    maskedAddress: "Đắk Nông",
    lat: 12.2646,
    lng: 107.6098,
    keywords: [
      "dak nong",
      "đắk nông",
      "gia nghia",
      "gia nghĩa",
      "xe đi đắk nông",
    ],
  }),

  province({
    provinceSlug: "quang-nam",
    name: "Quảng Nam",
    fullAddress: "Quảng Nam, Việt Nam",
    shortAddress: "Quảng Nam",
    maskedAddress: "Quảng Nam",
    lat: 15.5394,
    lng: 108.0191,
    keywords: [
      "quang nam",
      "quảng nam",
      "hoi an",
      "hội an",
      "chu lai",
      "xe đi quảng nam",
    ],
  }),
    // =========================
  // BLOCK C - MIỀN NAM
  // =========================

  province({
    provinceSlug: "tp-hcm",
    name: "TP.HCM",
    fullAddress: "TP.HCM, Việt Nam",
    shortAddress: "TP.HCM",
    maskedAddress: "TP.HCM",
    lat: 10.8231,
    lng: 106.6297,
    keywords: [
      "tphcm",
      "tp hcm",
      "ho chi minh",
      "hồ chí minh",
      "sai gon",
      "sài gòn",
      "xe đi tphcm",
    ],
  }),

  province({
    provinceSlug: "dong-nai",
    name: "Đồng Nai",
    fullAddress: "Đồng Nai, Việt Nam",
    shortAddress: "Đồng Nai",
    maskedAddress: "Đồng Nai",
    lat: 10.9453,
    lng: 106.8246,
    keywords: [
      "dong nai",
      "đồng nai",
      "bien hoa",
      "biên hòa",
      "long thanh",
      "xe đi đồng nai",
    ],
  }),

  province({
    provinceSlug: "binh-duong",
    name: "Bình Dương",
    fullAddress: "Bình Dương, Việt Nam",
    shortAddress: "Bình Dương",
    maskedAddress: "Bình Dương",
    lat: 10.9804,
    lng: 106.6519,
    keywords: [
      "binh duong",
      "bình dương",
      "thu dau mot",
      "thủ dầu một",
      "xe đi bình dương",
    ],
  }),

  province({
    provinceSlug: "tay-ninh",
    name: "Tây Ninh",
    fullAddress: "Tây Ninh, Việt Nam",
    shortAddress: "Tây Ninh",
    maskedAddress: "Tây Ninh",
    lat: 11.3100,
    lng: 106.1000,
    keywords: [
      "tay ninh",
      "tây ninh",
      "moc bai",
      "mộc bài",
      "xe đi tây ninh",
    ],
  }),

  province({
    provinceSlug: "binh-phuoc",
    name: "Bình Phước",
    fullAddress: "Bình Phước, Việt Nam",
    shortAddress: "Bình Phước",
    maskedAddress: "Bình Phước",
    lat: 11.7512,
    lng: 106.7235,
    keywords: [
      "binh phuoc",
      "bình phước",
      "dong xoai",
      "đồng xoài",
      "xe đi bình phước",
    ],
  }),

  province({
    provinceSlug: "ba-ria-vung-tau",
    name: "Bà Rịa - Vũng Tàu",
    fullAddress: "Bà Rịa - Vũng Tàu, Việt Nam",
    shortAddress: "Bà Rịa - Vũng Tàu",
    maskedAddress: "Bà Rịa - Vũng Tàu",
    lat: 10.5417,
    lng: 107.2429,
    keywords: [
      "vung tau",
      "vũng tàu",
      "ba ria",
      "bà rịa",
      "ho tram",
      "hồ tràm",
      "xe đi vũng tàu",
    ],
  }),

  province({
    provinceSlug: "can-tho",
    name: "Cần Thơ",
    fullAddress: "Cần Thơ, Việt Nam",
    shortAddress: "Cần Thơ",
    maskedAddress: "Cần Thơ",
    lat: 10.0452,
    lng: 105.7469,
    keywords: [
      "can tho",
      "cần thơ",
      "ninh kieu",
      "ninh kiều",
      "xe đi cần thơ",
    ],
  }),

  province({
    provinceSlug: "vinh-long",
    name: "Vĩnh Long",
    fullAddress: "Vĩnh Long, Việt Nam",
    shortAddress: "Vĩnh Long",
    maskedAddress: "Vĩnh Long",
    lat: 10.2537,
    lng: 105.9722,
    keywords: [
      "vinh long",
      "vĩnh long",
      "xe đi vĩnh long",
    ],
  }),

  province({
    provinceSlug: "dong-thap",
    name: "Đồng Tháp",
    fullAddress: "Đồng Tháp, Việt Nam",
    shortAddress: "Đồng Tháp",
    maskedAddress: "Đồng Tháp",
    lat: 10.4938,
    lng: 105.6881,
    keywords: [
      "dong thap",
      "đồng tháp",
      "cao lanh",
      "cao lãnh",
      "xe đi đồng tháp",
    ],
  }),

  province({
    provinceSlug: "an-giang",
    name: "An Giang",
    fullAddress: "An Giang, Việt Nam",
    shortAddress: "An Giang",
    maskedAddress: "An Giang",
    lat: 10.5216,
    lng: 105.1259,
    keywords: [
      "an giang",
      "chau doc",
      "châu đốc",
      "long xuyen",
      "long xuyên",
      "xe đi an giang",
    ],
  }),

  province({
    provinceSlug: "kien-giang",
    name: "Kiên Giang",
    fullAddress: "Kiên Giang, Việt Nam",
    shortAddress: "Kiên Giang",
    maskedAddress: "Kiên Giang",
    lat: 10.0125,
    lng: 105.0808,
    keywords: [
      "kien giang",
      "kiên giang",
      "phu quoc",
      "phú quốc",
      "rach gia",
      "rạch giá",
      "xe đi kiên giang",
    ],
  }),

  province({
    provinceSlug: "ca-mau",
    name: "Cà Mau",
    fullAddress: "Cà Mau, Việt Nam",
    shortAddress: "Cà Mau",
    maskedAddress: "Cà Mau",
    lat: 9.1768,
    lng: 105.1524,
    keywords: [
      "ca mau",
      "cà mau",
      "dat mui",
      "đất mũi",
      "xe đi cà mau",
    ],
  }),

  province({
    provinceSlug: "soc-trang",
    name: "Sóc Trăng",
    fullAddress: "Sóc Trăng, Việt Nam",
    shortAddress: "Sóc Trăng",
    maskedAddress: "Sóc Trăng",
    lat: 9.6037,
    lng: 105.9800,
    keywords: [
      "soc trang",
      "sóc trăng",
      "xe đi sóc trăng",
    ],
  }),

  province({
    provinceSlug: "bac-lieu",
    name: "Bạc Liêu",
    fullAddress: "Bạc Liêu, Việt Nam",
    shortAddress: "Bạc Liêu",
    maskedAddress: "Bạc Liêu",
    lat: 9.2940,
    lng: 105.7216,
    keywords: [
      "bac lieu",
      "bạc liêu",
      "xe đi bạc liêu",
    ],
  }),

  province({
    provinceSlug: "hau-giang",
    name: "Hậu Giang",
    fullAddress: "Hậu Giang, Việt Nam",
    shortAddress: "Hậu Giang",
    maskedAddress: "Hậu Giang",
    lat: 9.7841,
    lng: 105.4700,
    keywords: [
      "hau giang",
      "hậu giang",
      "xe đi hậu giang",
    ],
  }),

  province({
    provinceSlug: "ben-tre",
    name: "Bến Tre",
    fullAddress: "Bến Tre, Việt Nam",
    shortAddress: "Bến Tre",
    maskedAddress: "Bến Tre",
    lat: 10.2434,
    lng: 106.3755,
    keywords: [
      "ben tre",
      "bến tre",
      "xe đi bến tre",
    ],
  }),

  province({
    provinceSlug: "tra-vinh",
    name: "Trà Vinh",
    fullAddress: "Trà Vinh, Việt Nam",
    shortAddress: "Trà Vinh",
    maskedAddress: "Trà Vinh",
    lat: 9.9513,
    lng: 106.3346,
    keywords: [
      "tra vinh",
      "trà vinh",
      "xe đi trà vinh",
    ],
  }),

  province({
    provinceSlug: "tien-giang",
    name: "Tiền Giang",
    fullAddress: "Tiền Giang, Việt Nam",
    shortAddress: "Tiền Giang",
    maskedAddress: "Tiền Giang",
    lat: 10.4493,
    lng: 106.3420,
    keywords: [
      "tien giang",
      "tiền giang",
      "my tho",
      "mỹ tho",
      "xe đi tiền giang",
    ],
  }),

  province({
    provinceSlug: "long-an",
    name: "Long An",
    fullAddress: "Long An, Việt Nam",
    shortAddress: "Long An",
    maskedAddress: "Long An",
    lat: 10.6956,
    lng: 106.2431,
    keywords: [
      "long an",
      "tan an",
      "tân an",
      "xe đi long an",
    ],
  }),
];

export default PROVINCES;