// Hand-edited content for existing routes only. Never creates a route or changes indexing.
function routeEditorial({ title, description, h1, intro, trip, price, places, useCases, faqs, links, cta }) {
  return {
    title, description, h1, intro,
    sections: [
      { heading: trip.heading, paragraphs: trip.paragraphs, items: trip.items },
      { heading: "Giá và cách xem báo giá", paragraphs: [price] },
      { heading: "Điểm đón, điểm trả và nhu cầu phù hợp", items: [...places, ...useCases] },
      { heading: "Đặt chuyến cùng GoViet247", items: ["Chọn địa chỉ cụ thể, ngày giờ, loại xe và chiều đi để xem thông tin chuyến trước khi xác nhận.", "Nhắn Zalo trên trang nếu cần trao đổi về hành lý, giờ đón hoặc một điểm dừng chưa nhập được."] },
    ], faqs, links, cta,
  };
}

const editorialByPath = {
  "bien-hoa-di-bu-dop": {
    title: "Biên Hòa đi Bù Đốp: đặt xe riêng, xem giá theo chuyến",
    description: "Đặt xe riêng Biên Hòa đi Bù Đốp cùng GoViet247. Chọn điểm đón trả, xe 5/7/16 chỗ và lịch một chiều hoặc khứ hồi để xem giá theo hành trình của bạn.",
    h1: "Xe riêng Biên Hòa đi Bù Đốp",
    intro: [
      "Về thăm nhà ở Bù Đốp, đưa cả gia đình đi cùng hay đi làm việc rồi quay lại Biên Hòa trong ngày? Điều cần chốt trước là địa chỉ đến và giờ về, vì chuyến chỉ trả khách sẽ khác chuyến cần xe chờ. Nếu nhà người thân hoặc nơi làm việc khó tìm, hãy chuẩn bị ghim bản đồ và số điện thoại người đón để trao đổi trước chuyến đi.",
      "Trên GoViet247, bạn chọn địa chỉ đón tại Biên Hòa, địa chỉ trả ở Bù Đốp, ngày giờ và loại xe để xem báo giá. Với chuyến khứ hồi, nhập cả lịch quay về; nếu chưa biết giờ kết thúc công việc, hãy nhắn hỗ trợ trước khi chốt lịch thay vì mặc định xe sẽ chờ không giới hạn.",
    ],
    sections: [
      {
        heading: "Hành trình Biên Hòa → Bù Đốp cần chốt những gì?",
        paragraphs: [
          "Điểm đầu là địa chỉ bạn chọn ở Biên Hòa; điểm cuối là nhà riêng, nơi làm việc hoặc điểm hẹn cụ thể tại Bù Đốp. Chỉ nhập tên hai khu vực chưa đủ để xác định quãng đường và thời gian cho chuyến của bạn. Chọn đúng địa chỉ từ gợi ý trên trang đặt xe để hệ thống tính lộ trình bản đồ.",
          "Quãng đường và thời gian hiển thị sau khi chọn điểm đón trả là dự kiến. Khi có giờ hẹn làm việc hoặc cần về kịp một sự kiện gia đình, nên dự phòng thời gian đón khách, dừng nghỉ và tình trạng giao thông. Không lấy thời gian của một điểm đến ở trung tâm để áp dụng cho mọi địa chỉ tại Bù Đốp.",
        ],
        items: [
          "Một chiều: phù hợp khi về quê ở lại, có người đưa về hoặc chưa chốt ngày trở lại Biên Hòa.",
          "Khứ hồi: phù hợp khi đã có lịch đi và về; nhập giờ quay về dự kiến sau khi xe tới điểm đến.",
          "Có thêm điểm ghé: khai báo các điểm đến khi xem giá; nếu cần đón thêm người, trao đổi rõ địa chỉ và thứ tự đón với hỗ trợ.",
        ],
      },
      {
        heading: "Giá xe Biên Hòa đi Bù Đốp được tính thế nào?",
        paragraphs: [
          "GoViet247 không niêm yết một con số cố định trên trang này cho mọi chuyến Biên Hòa – Bù Đốp. Báo giá được tính theo loại xe và quãng đường của các địa chỉ bạn chọn. Lịch khứ hồi còn liên quan đến thời gian chờ hoặc qua đêm theo cấu hình giá áp dụng cho chuyến.",
          "Để so sánh phương án, giữ nguyên điểm đón trả và ngày giờ rồi lần lượt xem giá các loại xe. Nếu đổi địa chỉ trả, thêm điểm ghé hoặc đổi giờ về, hãy xem lại báo giá trước khi xác nhận. Với yêu cầu ngoài hành trình đã nhập, nhắn hỗ trợ để làm rõ chi phí và khả năng phục vụ.",
        ],
      },
      {
        heading: "Hẹn đón ở Biên Hòa, trả đúng điểm tại Bù Đốp",
        items: [
          "Đón tại nhà: ghi số nhà, tên đường và ghim bản đồ. Nếu hẻm khó quay đầu hoặc không phù hợp loại xe đã chọn, thống nhất điểm gặp dễ tiếp cận gần đó.",
          "Đón sau giờ làm ở Biên Hòa: ghi rõ cổng cơ quan hoặc nơi làm việc, giờ có thể ra xe và số điện thoại liên hệ; tránh chỉ ghi tên một khu vực rộng.",
          "Trả tại nhà người thân ở Bù Đốp: gửi vị trí chính xác và hướng dẫn đoạn đường cuối nếu cần, nhất là khi địa chỉ chưa được bản đồ nhận diện rõ.",
          "Trả tại nơi hẹn công việc: xác nhận cổng vào hoặc điểm gặp với người tiếp đón. Nếu còn đi thêm nơi khác, đưa các điểm đó vào kế hoạch trước khi đặt.",
        ],
      },
      {
        heading: "Chọn xe theo người đi và hành lý",
        paragraphs: [
          "Trang đặt xe có lựa chọn xe 5, 7 và 16 chỗ. Ngoài số người, hãy tính cả vali, đồ mang về quê và nhu cầu lên xuống xe của người lớn tuổi. Tên loại xe không có nghĩa mọi chỗ ngồi và toàn bộ hành lý của nhóm đều phù hợp; nếu mang nhiều đồ, hãy nhắn hỗ trợ để chọn xe trước khi đặt.",
          "Gia đình về thăm người thân nên chốt số người và đồ mang theo cho cả chiều về. Nhóm đi công việc nên thống nhất người đại diện liên hệ và lịch ghé từng nơi. Với người lớn tuổi hoặc trẻ nhỏ đi cùng, trao đổi nhu cầu dừng nghỉ trước chuyến để sắp xếp lịch phù hợp.",
        ],
      },
      {
        heading: "GoViet247 giúp bạn chuẩn bị chuyến đi ra sao?",
        items: [
          "Đặt xe riêng theo địa chỉ đón trả bạn chọn, thuận tiện khi điểm đến là nhà người thân hoặc nơi làm việc cụ thể tại Bù Đốp.",
          "Xem quãng đường dự kiến và báo giá trên trang đặt xe trước khi xác nhận, thay vì tự ước lượng từ tên tuyến.",
          "Chọn một chiều hoặc khứ hồi và loại xe trong cùng quy trình đặt chuyến.",
          "Có nút nhắn Zalo hỗ trợ ngay trên trang để trao đổi về điểm đón khó tìm, hành lý hoặc lịch về chưa chắc chắn.",
        ],
      },
    ],
    faqs: [
      {
        question: "Đi từ Biên Hòa tới Bù Đốp mất bao lâu?",
        answer: "Bạn cần chọn địa chỉ đón và trả cụ thể để xem thời gian dự kiến theo bản đồ trên trang đặt xe. Thời gian thực tế còn phụ thuộc giao thông và các lần dừng. Nếu có giờ hẹn ở Bù Đốp, hãy dự phòng thêm thời gian và trao đổi lịch trước chuyến.",
      },
      {
        question: "Về thăm nhà ở Bù Đốp nhưng chưa biết ngày về thì đặt thế nào?",
        answer: "Bạn có thể chọn chuyến một chiều Biên Hòa → Bù Đốp cho lịch đã chắc chắn. Khi có kế hoạch về, xem giá và đặt hành trình chiều ngược lại. Không nên chọn một giờ về tạm chỉ để lấy báo giá khứ hồi nếu lịch thực tế chưa rõ.",
      },
      {
        question: "Đi làm việc ở Bù Đốp rồi quay về trong ngày có cần nhập giờ về không?",
        answer: "Có. Với lựa chọn khứ hồi, hệ thống cần ngày giờ quay về để tính chuyến và thời gian chờ. Nếu cuộc hẹn có thể kéo dài, hãy trao đổi với hỗ trợ về lịch dự kiến và cách xử lý khi thay đổi giờ trước khi xác nhận.",
      },
      {
        question: "Nhà người thân ở Bù Đốp không hiện đúng trên bản đồ thì sao?",
        answer: "Nhờ người thân gửi ghim vị trí và mô tả đường vào, rồi nhắn hỗ trợ để xác nhận điểm trả. Không chọn một địa chỉ gần đó như thể đó là điểm cuối nếu xe còn phải đi thêm, vì quãng đường và giá có thể khác.",
      },
      {
        question: "Có thể đón người nhà ở hai địa chỉ tại Biên Hòa không?",
        answer: "Hãy gửi cả hai địa chỉ, số người tại mỗi điểm và giờ muốn khởi hành cho hỗ trợ để kiểm tra phương án. Cần chốt thứ tự đón và giá của hành trình có thêm điểm, tránh hiểu báo giá một điểm đón đã bao gồm mọi lần ghé.",
      },
    ],
    links: [
      { path: "/bien-hoa-di-bu-gia-map", label: "Biên Hòa đi Bù Gia Mập — nếu đây mới là điểm đến của bạn" },
      { path: "/thue-xe-di-tinh", label: "Thông tin thuê xe đi tỉnh" },
      { path: "/xe-7-cho", label: "Tìm hiểu xe 7 chỗ cho chuyến gia đình" },
    ],
    cta: "Chốt điểm đón ở Biên Hòa và địa chỉ đến tại Bù Đốp, chọn ngày giờ cùng loại xe để xem báo giá cho chuyến của bạn.",
  },
  "thue-xe-di-benh-vien-shing-mark": routeEditorial({
    title: "Thuê xe đi Bệnh viện Shing Mark: chủ động giờ khám", description: "Đặt xe riêng từ TP.HCM đi Bệnh viện Đại học Y Dược Shing Mark. Chọn giờ hẹn khám, điểm đón và lịch về để xem giá theo chuyến.", h1: "Xe riêng đi Bệnh viện Shing Mark",
    intro: ["Đi khám, tái khám hoặc đưa người thân đến Bệnh viện Shing Mark cần chủ động giờ có mặt hơn là chỉ chọn tên điểm đến. Hãy chốt giờ hẹn, số người đi cùng và người liên hệ tại bệnh viện trước khi đặt xe.", "Nếu khám trong ngày, chỉ chọn khứ hồi khi đã có giờ kết thúc dự kiến. Trường hợp bác sĩ chưa hẹn giờ xong hoặc có thể chờ lâu, nhắn hỗ trợ để trao đổi lịch xe phù hợp."],
    trip:{heading:"Chuẩn bị cho chuyến đi khám", paragraphs:["Nhập địa chỉ đón chính xác ở TP.HCM và chọn bệnh viện từ bản đồ để hệ thống tính quãng đường. Nên đến sớm hơn giờ hẹn, đặc biệt khi đi cùng người lớn tuổi hoặc cần làm thủ tục."], items:["Ghi rõ cổng hoặc khu đón trả mong muốn nếu đã được bệnh viện hướng dẫn.","Mang theo giấy hẹn, giấy tờ khám và thuốc cần dùng; không để các việc này đến lúc xe đã tới mới chuẩn bị."]},
    price:"Giá phụ thuộc địa chỉ đón, thời gian, loại xe và lựa chọn một chiều hoặc khứ hồi. Trang này không niêm yết một giá cố định cho mọi chuyến đi bệnh viện.", places:["Đón tại nhà, chung cư, khách sạn hoặc văn phòng ở TP.HCM.","Trả tại điểm hẹn có thể tiếp cận được quanh Bệnh viện Shing Mark; xác nhận lại với người nhà nếu cần."], useCases:["Phù hợp bệnh nhân tái khám, người nhà đưa đón và khách cần đi viện theo giờ hẹn."],
    faqs:[{question:"Nên đặt xe trước giờ khám bao lâu?",answer:"Chọn giờ đón có dự phòng cho di chuyển và thủ tục. Thời gian cụ thể hiển thị theo địa chỉ thực tế trên trang đặt xe."},{question:"Khám xong chưa biết giờ về thì sao?",answer:"Đặt một chiều hoặc trao đổi với hỗ trợ về thời gian dự kiến; không mặc định xe chờ không giới hạn."},{question:"Có thể đi cùng người nhà không?",answer:"Có, hãy chọn xe dựa trên số người và hành lý, đồng thời ghi rõ nhu cầu hỗ trợ khi đặt."}], links:[{path:"/thue-xe-di-tinh",label:"Thuê xe đi tỉnh"},{path:"/xe-7-cho",label:"Xe 7 chỗ cho gia đình"},{path:"/thue-xe-san-bay-tan-son-nhat-di-trang-bom",label:"Xe đi Đồng Nai"}], cta:"Nhập giờ hẹn khám, địa chỉ đón và điểm trả để xem giá chuyến đi bệnh viện."}),
  "xe-tu-dai-hoc-ton-duc-thang-di-vung-tau": routeEditorial({
    title:"Xe Đại học Tôn Đức Thắng đi Vũng Tàu: chủ động lịch đoàn",description:"Đặt xe riêng từ Đại học Tôn Đức Thắng đi Vũng Tàu cho nhóm bạn, sinh viên và giảng viên. Chọn điểm tập trung, xe và lịch về để xem giá.",h1:"Xe từ Đại học Tôn Đức Thắng đi Vũng Tàu",intro:["Chuyến đi Vũng Tàu từ Đại học Tôn Đức Thắng thường cần chốt đúng điểm tập trung, số người và hành lý trước khi cả nhóm xuất phát. Một người đại diện nên giữ liên lạc và gửi vị trí đón rõ ràng.","Nếu đi hoạt động ngoại khóa hoặc du lịch trong ngày, lịch về cần được thống nhất trước để tính chuyến khứ hồi chính xác."],trip:{heading:"Đi theo nhóm từ trường đến Vũng Tàu",paragraphs:["Điểm đón có thể là khu vực trường hoặc một điểm gặp đã thống nhất. Điểm trả cần ghi cụ thể: khách sạn, bãi biển, nhà hàng hay địa chỉ tại Vũng Tàu."],items:["Chọn xe theo tổng số người, vali và dụng cụ mang theo.","Ghi các điểm ghé trong lịch trình trước khi xem giá."]},price:"Poster giá Sài Gòn ↔ Vũng Tàu ghi 700.000đ xe 5 chỗ và 790.000đ xe 7 chỗ một chiều. Đại học Tôn Đức Thắng là điểm đón cụ thể nên cần xem báo giá thực tế, không coi đây là giá cố định.",places:["Đón tại điểm tập trung gần trường theo vị trí có thể dừng xe.","Trả tại khách sạn, homestay hoặc địa điểm hoạt động ở Vũng Tàu."],useCases:["Phù hợp nhóm bạn cuối tuần, giảng viên, câu lạc bộ và chương trình ngoại khóa."],faqs:[{question:"Có thể đón cả nhóm ở nhiều điểm không?",answer:"Có thể trao đổi các điểm đón và thứ tự đón trước khi xác nhận; báo giá một điểm không tự bao gồm điểm ghé thêm."},{question:"Đi trong ngày có cần giờ về?",answer:"Có. Khứ hồi cần ngày giờ quay về để hệ thống tính chuyến."},{question:"Chọn xe nào cho nhiều hành lý?",answer:"Cân nhắc cả hành lý ngoài số người và nhắn hỗ trợ khi mang đồ cồng kềnh."}],links:[{path:"/thue-xe-tu-quan-1-di-vung-tau",label:"Xe Quận 1 đi Vũng Tàu"},{path:"/vung-tau",label:"Các tuyến xe đi Vũng Tàu"},{path:"/xe-16-cho",label:"Xe 16 chỗ"}],cta:"Chốt điểm tập trung, số người và lịch về để xem giá xe đi Vũng Tàu."}),
  "bien-hoa-di-bu-gia-map": routeEditorial({title:"Biên Hòa đi Bù Gia Mập: xe riêng theo lịch của bạn",description:"Đặt xe riêng Biên Hòa đi Bù Gia Mập. Chọn địa chỉ đón trả, loại xe và chuyến một chiều hoặc khứ hồi để xem giá theo hành trình.",h1:"Xe riêng Biên Hòa đi Bù Gia Mập",intro:["Đi Bù Gia Mập để về nhà, làm việc hay thăm người thân cần xác định đúng địa chỉ cuối vì khu vực đến có thể xa trung tâm. Chuẩn bị ghim vị trí và số điện thoại người đón.","Nếu quay lại Biên Hòa cùng ngày, hãy nhập giờ về thực tế thay vì ước lượng xe chờ."],trip:{heading:"Chốt lộ trình trước khi xuất phát",paragraphs:["Trang đặt xe tính quãng đường từ địa chỉ đón thực tế tại Biên Hòa đến điểm trả bạn chọn tại Bù Gia Mập."],items:["Ghi điểm hẹn dễ dừng xe nếu nhà trong hẻm hoặc đường vào khó tìm.","Khai báo điểm ghé và hành lý trước khi xem giá."]},price:"Chưa có bảng giá xác thực riêng cho tuyến này. Giá được tính theo địa chỉ, loại xe, chiều đi và lịch quay về nếu có.",places:["Đón tại nhà hoặc nơi làm việc ở Biên Hòa.","Trả tại nhà người thân, nơi công tác hoặc điểm hẹn cụ thể tại Bù Gia Mập."],useCases:["Phù hợp về quê, công tác và chuyến đi gia đình."],faqs:[{question:"Có thể đặt khứ hồi không?",answer:"Có, khi đã biết ngày giờ quay về."},{question:"Đường vào nhà khó tìm?",answer:"Gửi ghim vị trí và hướng dẫn đoạn cuối cho hỗ trợ."},{question:"Giá có cố định không?",answer:"Không, xem giá sau khi nhập địa chỉ và lịch đi."}],links:[{path:"/bien-hoa-di-bu-dop",label:"Biên Hòa đi Bù Đốp"},{path:"/thue-xe-di-tinh",label:"Thuê xe đi tỉnh"},{path:"/xe-7-cho",label:"Xe 7 chỗ"}],cta:"Nhập địa chỉ Biên Hòa và Bù Gia Mập để xem giá chuyến đi."}),
  "thue-xe-phuong-phu-nhuan-di-vung-tau": routeEditorial({title:"Thuê xe Phú Nhuận đi Vũng Tàu: đón tận điểm hẹn",description:"Xe riêng từ phường Phú Nhuận đi Vũng Tàu cho gia đình, khách sạn và văn phòng. Xem giá theo điểm đón, lịch đi và loại xe.",h1:"Thuê xe phường Phú Nhuận đi Vũng Tàu",intro:["Từ Phú Nhuận đi Vũng Tàu, điểm đón thường là nhà, khách sạn hoặc văn phòng. Ghi đúng địa chỉ và giờ xuất phát để cả nhóm không phải đổi điểm hẹn vào phút cuối.","Nếu đến resort hoặc khách sạn, nhập tên và vị trí chính xác thay vì chỉ chọn Vũng Tàu."],trip:{heading:"Đi biển hay đi công tác từ Phú Nhuận",paragraphs:["Chuyến một chiều phù hợp khi có lịch ở lại; khứ hồi cần giờ quay về. Thêm điểm đón bạn bè hoặc điểm trả khác cần được đưa vào hành trình."],items:["Chọn xe theo người và vali.","Chốt cổng đón nếu điểm hẹn là tòa nhà hoặc khách sạn."]},price:"Bảng giá Sài Gòn ↔ Vũng Tàu một chiều tham khảo: xe 5 chỗ 700.000đ, xe 7 chỗ 790.000đ. Giá thực tế thay đổi theo điểm đón/trả, nên xem báo giá trước khi xác nhận.",places:["Đón tại nhà, văn phòng hoặc khách sạn ở Phú Nhuận.","Trả tại Bãi Sau, Bãi Trước, khách sạn hoặc địa chỉ cụ thể."],useCases:["Phù hợp cuối tuần, đón khách, công tác và nghỉ biển."],faqs:[{question:"Có đón tại sân bay gần Phú Nhuận không?",answer:"Hãy nhập đúng điểm đón hoặc chọn trang sân bay để xem báo giá theo hành trình."},{question:"Giá 700.000đ áp dụng mọi địa chỉ?",answer:"Không. Đây là giá tham khảo Sài Gòn ↔ Vũng Tàu; điểm đón/trả cụ thể quyết định giá hiển thị."},{question:"Có thể về muộn không?",answer:"Khứ hồi cần giờ về; trao đổi trước nếu lịch thay đổi."}],links:[{path:"/thue-xe-tu-quan-1-di-vung-tau",label:"Xe Quận 1 đi Vũng Tàu"},{path:"/xe-tu-nha-ga-t3-di-vung-tau",label:"Xe nhà ga T3 đi Vũng Tàu"},{path:"/vung-tau",label:"Xe đi Vũng Tàu"}],cta:"Nhập điểm đón ở Phú Nhuận và nơi trả tại Vũng Tàu để xem giá."}),
  "xe-di-an-giang-tu-long-an": routeEditorial({title:"Xe Long An đi An Giang: chọn đúng điểm đến",description:"Đặt xe riêng Long An đi An Giang cho chuyến về quê, công tác hoặc đi lễ. Chọn Long Xuyên, Châu Đốc hay địa chỉ cụ thể để xem giá.",h1:"Xe đi An Giang từ Long An",intro:["An Giang là cả một tỉnh nên giá và thời gian sẽ khác giữa Long Xuyên, Châu Đốc, Tân Châu hay một địa chỉ ở huyện. Hãy chọn đúng điểm cuối thay vì chỉ nhập “An Giang”.","Nếu đi lễ hoặc về quê vào ngày đông khách, chốt giờ đón và số người sớm để kiểm tra phương án xe."],trip:{heading:"Một tuyến, nhiều điểm đến",paragraphs:["Địa chỉ đón ở Long An và điểm trả cụ thể tại An Giang là dữ liệu cần thiết để hệ thống tính chuyến."],items:["Ghi rõ nơi ghé nếu cần thăm nhiều nhà.","Chọn khứ hồi khi lịch trở lại Long An đã chắc chắn."]},price:"Không có giá cố định Long An → An Giang vì điểm đến trong tỉnh khác nhau. Xem giá sau khi nhập địa chỉ, loại xe và thời gian.",places:["Đón tại nhà, công ty hoặc điểm hẹn ở Long An.","Trả tại Long Xuyên, Châu Đốc, Tân Châu hoặc địa chỉ được chọn trên bản đồ."],useCases:["Phù hợp về quê, công tác, đi lễ và thăm người thân."],faqs:[{question:"Đi Châu Đốc có cùng giá đi Long Xuyên không?",answer:"Không thể mặc định như vậy; hãy chọn đúng điểm trả."},{question:"Có ghé nhiều điểm không?",answer:"Khai báo các điểm ghé trước khi xác nhận."},{question:"Khi nào cần đặt khứ hồi?",answer:"Khi đã có lịch quay lại Long An."}],links:[{path:"/an-giang",label:"Xe đi An Giang"},{path:"/thue-xe-di-tinh",label:"Thuê xe đi tỉnh"},{path:"/thue-xe-tu-cu-chi-di-hong-ngu-dong-thap",label:"Xe đi Hồng Ngự"}],cta:"Chọn chính xác địa chỉ tại An Giang để xem báo giá."}),
  "xe-di-lan-rung-resort-phuoc-hai": routeEditorial({title:"Xe đi Lan Rừng Resort Phước Hải: đón trả theo giờ nhận phòng",description:"Đặt xe riêng TP.HCM đi Lan Rừng Resort Phước Hải. Chọn điểm đón, giờ nhận phòng và chuyến khứ hồi để xem giá.",h1:"Xe riêng đi Lan Rừng Resort Phước Hải",intro:["Đi resort thuận tiện nhất khi giờ xe đến khớp giờ nhận phòng hoặc lịch hoạt động của nhóm. Gửi đúng vị trí resort, số người và hành lý để chọn xe.","Nếu về trong ngày hoặc check-out muộn, ghi giờ về thực tế; không nên mặc định xe sẽ chờ trong thời gian nghỉ dưỡng."],trip:{heading:"Đi Phước Hải theo lịch resort",paragraphs:["Điểm đón tại TP.HCM có thể là nhà, khách sạn hoặc văn phòng. Điểm trả cần là Lan Rừng Resort Phước Hải, không chỉ tên khu vực Phước Hải."],items:["Tính cả vali, xe đẩy trẻ em hoặc đồ đi biển.","Chốt giờ đón theo check-in/check-out." ]},price:"Chưa có bảng giá xác thực riêng tới Lan Rừng Resort. Báo giá thay đổi theo điểm đón, xe và lịch một chiều hoặc khứ hồi.",places:["Đón tại nhà, khách sạn hoặc văn phòng TP.HCM.","Trả tại sảnh resort hoặc điểm hẹn phù hợp với quy định đón trả."],useCases:["Phù hợp nghỉ dưỡng gia đình, nhóm bạn và chuyến cuối tuần."],faqs:[{question:"Có đón sớm để kịp check-in không?",answer:"Hãy chọn giờ đón phù hợp lịch của bạn."},{question:"Xe có chờ khi nghỉ tại resort không?",answer:"Cần trao đổi lịch khứ hồi hoặc thời gian chờ trước."},{question:"Mang nhiều đồ biển chọn xe nào?",answer:"Chọn xe theo số người lẫn hành lý; nhắn hỗ trợ khi có đồ cồng kềnh."}],links:[{path:"/xe-dua-don-resort-long-hai",label:"Xe đưa đón resort Long Hải"},{path:"/dat-xe-di-carmelina-beach-resort",label:"Xe đi Carmelina Beach Resort"},{path:"/ho-tram",label:"Xe đi Hồ Tràm"}],cta:"Nhập điểm đón và giờ nhận phòng để xem giá đi Lan Rừng Resort."}),
  "thue-xe-tu-cu-chi-di-hong-ngu-dong-thap": routeEditorial({title:"Thuê xe Củ Chi đi Hồng Ngự: chốt đúng điểm trả",description:"Xe riêng Củ Chi đi Hồng Ngự, Đồng Tháp cho về quê và công tác. Nhập địa chỉ đón trả, xe và lịch về để xem giá theo chuyến.",h1:"Thuê xe Củ Chi đi Hồng Ngự Đồng Tháp",intro:["Tuyến Củ Chi – Hồng Ngự phù hợp khi cần đi thẳng đến nhà người thân, cơ quan hay điểm hẹn tại Hồng Ngự. Chuẩn bị ghim vị trí vì điểm trả có thể ngoài khu trung tâm.","Nếu đón thêm người tại Củ Chi hoặc ghé dọc đường, đưa các điểm đó vào kế hoạch trước khi chốt."],trip:{heading:"Đi Đồng Tháp từ Củ Chi",paragraphs:["Hệ thống cần địa chỉ cụ thể để tính hành trình; tên thành phố chỉ là điểm tham khảo."],items:["Chọn chiều đi hoặc khứ hồi theo lịch thực tế.","Ghi số điện thoại người đón tại Hồng Ngự nếu địa chỉ khó tìm."]},price:"Chưa có giá niêm yết đúng tuyến Củ Chi – Hồng Ngự. Giá được tính theo địa chỉ, loại xe, điểm ghé và thời gian.",places:["Đón tại nhà, khu dân cư hoặc nơi làm việc ở Củ Chi.","Trả tại TP Hồng Ngự hoặc địa chỉ cụ thể ở Đồng Tháp."],useCases:["Phù hợp về quê, thăm người thân và công tác."],faqs:[{question:"Có thể chở nhiều hành lý không?",answer:"Chọn xe phù hợp với số người và hành lý, trao đổi trước nếu mang đồ cồng kềnh."},{question:"Đi nhiều điểm tại Hồng Ngự?",answer:"Khai báo các điểm ghé để báo giá đúng."},{question:"Giá có cố định theo thành phố không?",answer:"Không, địa chỉ cuối cùng quyết định quãng đường thực tế."}],links:[{path:"/dong-thap",label:"Xe đi Đồng Tháp"},{path:"/xe-di-an-giang-tu-long-an",label:"Xe Long An đi An Giang"},{path:"/thue-xe-di-tinh",label:"Thuê xe đi tỉnh"}],cta:"Nhập địa chỉ tại Củ Chi và Hồng Ngự để xem giá chuyến đi."}),
  "xe-tu-san-bay-cam-ranh-di-doc-let": routeEditorial({title:"Xe sân bay Cam Ranh đi Dốc Lết: đón theo giờ hạ cánh",description:"Đặt xe riêng từ sân bay Cam Ranh đi Dốc Lết. Nhập giờ bay, số chuyến và nơi lưu trú để xem giá theo hành trình.",h1:"Xe từ sân bay Cam Ranh đi Dốc Lết",intro:["Sau chuyến bay, thông tin quan trọng nhất là giờ hạ cánh thực tế, số hành khách và hành lý. Gửi số chuyến bay khi đặt để việc phối hợp đón dễ hơn.","Dốc Lết có nhiều khách sạn và khu lưu trú; hãy chọn đúng địa chỉ thay vì chỉ chọn tên bãi biển."],trip:{heading:"Từ cửa ra sân bay đến nơi lưu trú",paragraphs:["Chọn điểm gặp phù hợp tại sân bay và địa chỉ khách sạn/resort ở Dốc Lết. Dự phòng thời gian lấy hành lý trước giờ xe đón."],items:["Ghi số người, vali và đồ thể thao nếu có.","Cập nhật hỗ trợ nếu giờ bay thay đổi."]},price:"Chưa có bảng giá xác thực riêng sân bay Cam Ranh – Dốc Lết. Giá hiển thị theo điểm trả, giờ đón và loại xe.",places:["Đón tại khu vực được hẹn ở sân bay Cam Ranh.","Trả tại khách sạn, resort hoặc địa chỉ cụ thể tại Dốc Lết."],useCases:["Phù hợp khách bay đến nghỉ biển, gia đình và nhóm có hành lý."],faqs:[{question:"Máy bay trễ thì sao?",answer:"Thông báo hỗ trợ sớm kèm số chuyến bay để điều phối."},{question:"Có cần ghi tên khách sạn?",answer:"Có, tên và ghim vị trí giúp tính lộ trình đúng."},{question:"Đi chung đoàn chọn xe thế nào?",answer:"Dựa trên số người và hành lý, không chỉ số ghế."}],links:[{path:"/nha-trang",label:"Xe đi Nha Trang"},{path:"/xe-dua-don-san-bay",label:"Xe đưa đón sân bay"},{path:"/xe-7-cho",label:"Xe 7 chỗ"}],cta:"Nhập giờ hạ cánh và địa chỉ Dốc Lết để xem giá."}),
  "don-san-bay-tan-son-nhat-di-ben-tre": routeEditorial({title:"Đón sân bay Tân Sơn Nhất đi Bến Tre: theo giờ bay",description:"Đặt xe riêng đón từ sân bay Tân Sơn Nhất đi Bến Tre. Nhập giờ hạ cánh, hành lý và địa chỉ trả để xem giá.",h1:"Xe đón sân bay Tân Sơn Nhất đi Bến Tre",intro:["Chuyến sân bay đi Bến Tre nên có số chuyến bay, giờ hạ cánh và số hành lý để sắp xếp điểm gặp. Đừng chỉ chọn “Bến Tre” nếu bạn cần về một huyện hoặc địa chỉ cụ thể.","Nếu đón người thân lần đầu về nước, thống nhất số điện thoại hoặc điểm nhận diện tại sân bay trước chuyến."],trip:{heading:"Đón khách sau khi hạ cánh",paragraphs:["Dự phòng thời gian lấy hành lý và di chuyển ra điểm gặp. Chọn đúng địa chỉ ở Bến Tre để xem quãng đường và giá."],items:["Gửi số chuyến bay khi đặt.","Chọn xe theo số người và vali."]},price:"Poster Sài Gòn ↔ Bến Tre một chiều ghi 640.000đ xe 5 chỗ, 720.000đ xe 7 chỗ. Điểm đón sân bay có thể khác, nên đây chỉ là mức tham khảo; xem giá thực tế trước khi đặt.",places:["Đón tại điểm hẹn sân bay Tân Sơn Nhất.","Trả tại nhà, khách sạn hoặc địa chỉ cụ thể ở Bến Tre."],useCases:["Phù hợp khách vừa hạ cánh, về quê và đi công tác."],faqs:[{question:"Có theo dõi giờ bay không?",answer:"Gửi số chuyến bay và báo hỗ trợ khi có thay đổi."},{question:"Giá poster có áp dụng sân bay?",answer:"Không mặc định; đó là giá tham khảo Sài Gòn ↔ Bến Tre."},{question:"Có ghé Mỹ Tho không?",answer:"Hãy thêm điểm ghé vào hành trình để báo giá đúng."}],links:[{path:"/ben-tre",label:"Xe đi Bến Tre"},{path:"/thue-xe-tu-san-bay-tan-son-nhat-di-can-tho",label:"Xe sân bay đi Cần Thơ"},{path:"/xe-dua-don-san-bay",label:"Xe đưa đón sân bay"}],cta:"Nhập giờ bay và địa chỉ Bến Tre để xem giá chuyến đón sân bay."}),
  "thue-xe-san-bay-tan-son-nhat-di-trang-bom": routeEditorial({title:"Xe sân bay Tân Sơn Nhất đi Trảng Bom: theo giờ bay",description:"Đặt xe riêng từ sân bay Tân Sơn Nhất đi Trảng Bom cho về nhà, công tác và chuyên gia. Nhập giờ hạ cánh để xem giá.",h1:"Thuê xe sân bay Tân Sơn Nhất đi Trảng Bom",intro:["Từ sân bay đi Trảng Bom, điểm trả có thể là nhà riêng, khách sạn hay khu công nghiệp. Chọn địa chỉ chính xác và ghi giờ hạ cánh để điều phối chuyến.","Nếu đi công tác, nên ghi cổng công ty hoặc khu công nghiệp thay vì chỉ nhập tên Trảng Bom."],trip:{heading:"Đón sân bay, trả đúng địa chỉ",paragraphs:["Dự phòng thời gian lấy hành lý trước khi hẹn xe. Hệ thống tính giá theo điểm đón, điểm trả và loại xe."],items:["Gửi số chuyến bay nếu có.","Chọn xe theo hành khách và hành lý."]},price:"Chưa có bảng giá xác thực riêng sân bay – Trảng Bom. Xem báo giá theo địa chỉ và giờ đón thực tế.",places:["Đón ở điểm gặp sân bay.","Trả tại nhà, công ty hoặc khách sạn ở Trảng Bom."],useCases:["Phù hợp chuyên gia, khách công tác và người về thăm gia đình."],faqs:[{question:"Trễ chuyến bay thì sao?",answer:"Báo hỗ trợ sớm kèm số chuyến bay."},{question:"Có đón nhiều người?",answer:"Chọn xe theo số người và vali."},{question:"Công ty khó tìm?",answer:"Gửi ghim vị trí và cổng vào."}],links:[{path:"/thue-xe-di-benh-vien-shing-mark",label:"Xe đi Bệnh viện Shing Mark"},{path:"/xe-dua-don-san-bay",label:"Xe đưa đón sân bay"},{path:"/dong-nai",label:"Xe đi Đồng Nai"}],cta:"Nhập giờ hạ cánh và địa chỉ Trảng Bom để xem giá."}),
  "di-an-di-dong-xoai": routeEditorial({title:"Xe Dĩ An đi Đồng Xoài: báo giá theo địa chỉ",description:"Đặt xe riêng Dĩ An đi Đồng Xoài cho về quê hoặc công tác. Chọn điểm đón trả, loại xe và lịch về để xem giá.",h1:"Xe riêng Dĩ An đi Đồng Xoài",intro:["Dĩ An đi Đồng Xoài phù hợp cho chuyến về nhà, gặp đối tác hoặc đi việc trong ngày. Địa chỉ cụ thể ở Đồng Xoài giúp hệ thống tính hành trình đúng hơn.","Nếu cần quay lại Dĩ An, chốt giờ về và điểm hẹn trước khi chọn khứ hồi."],trip:{heading:"Chủ động giờ đi và điểm trả",paragraphs:["Nhập đúng nhà, văn phòng hoặc địa điểm hẹn ở hai đầu chuyến. Có điểm ghé cần được đưa vào hành trình."],items:["Chọn xe theo số người và hành lý.","Dự phòng thời gian nếu có giờ hẹn quan trọng."]},price:"Không có giá cố định cho mọi địa chỉ Dĩ An – Đồng Xoài; báo giá thay đổi theo hành trình và loại xe.",places:["Đón tại nhà, chung cư hoặc công ty ở Dĩ An.","Trả tại nhà người thân, cơ quan hoặc điểm hẹn ở Đồng Xoài."],useCases:["Phù hợp công tác, về quê và thăm người thân."],faqs:[{question:"Có đi về trong ngày không?",answer:"Có thể chọn khứ hồi khi đã biết giờ về."},{question:"Đi nhiều điểm?",answer:"Khai báo điểm ghé để xem giá đúng."},{question:"Giá trước khi đặt?",answer:"Nhập địa chỉ và lịch đi để xem giá."}],links:[{path:"/bien-hoa-di-bu-gia-map",label:"Xe Biên Hòa đi Bù Gia Mập"},{path:"/thue-xe-di-tinh",label:"Thuê xe đi tỉnh"},{path:"/xe-7-cho",label:"Xe 7 chỗ"}],cta:"Nhập địa chỉ Dĩ An và Đồng Xoài để xem giá."}),
  "dat-xe-di-carmelina-beach-resort": routeEditorial({title:"Xe đi Carmelina Beach Resort: theo lịch nhận phòng",description:"Đặt xe riêng TP.HCM đi Carmelina Beach Resort. Chọn điểm đón, giờ nhận phòng và xe phù hợp để xem giá.",h1:"Đặt xe đi Carmelina Beach Resort",intro:["Carmelina Beach Resort phù hợp chuyến nghỉ ngắn ngày nên giờ xe đến cần khớp check-in của bạn. Chọn đúng vị trí resort và tính cả hành lý, đồ biển hoặc trẻ nhỏ.","Nếu đặt khứ hồi, ghi giờ check-out hoặc giờ hẹn về thay vì để lịch chờ mở."],trip:{heading:"Đi resort theo lịch của gia đình",paragraphs:["Nhập địa chỉ đón ở TP.HCM và điểm trả đúng tại resort để xem quãng đường, thời gian và giá."],items:["Chốt giờ đón theo lịch nhận phòng.","Chọn xe theo người và hành lý."]},price:"Chưa có bảng giá xác thực riêng tới Carmelina Beach Resort. Giá phụ thuộc điểm đón, loại xe và lịch một chiều/khứ hồi.",places:["Đón tại nhà, khách sạn hoặc văn phòng TP.HCM.","Trả tại resort hoặc điểm hẹn được xác nhận."],useCases:["Phù hợp gia đình, nhóm bạn và nghỉ dưỡng cuối tuần."],faqs:[{question:"Xe có chờ ở resort?",answer:"Cần chốt lịch khứ hồi hoặc trao đổi thời gian chờ trước."},{question:"Mang xe đẩy trẻ em?",answer:"Ghi rõ khi đặt để chọn xe."},{question:"Có đi nhiều resort?",answer:"Thêm các điểm ghé để báo giá đúng."}],links:[{path:"/xe-di-lan-rung-resort-phuoc-hai",label:"Xe đi Lan Rừng Resort"},{path:"/xe-dua-don-resort-long-hai",label:"Xe resort Long Hải"},{path:"/ho-tram",label:"Xe đi Hồ Tràm"}],cta:"Chọn giờ nhận phòng và điểm đón để xem giá xe đi Carmelina."}),
  "long-thanh-di-vung-tau": routeEditorial({title:"Xe Long Thành đi Vũng Tàu: từ nhà, sân bay hay khu công nghiệp",description:"Đặt xe riêng Long Thành đi Vũng Tàu. Chọn điểm đón cụ thể, địa chỉ trả và xe để xem giá theo hành trình.",h1:"Xe Long Thành đi Vũng Tàu",intro:["Long Thành có điểm đón ở nhà, khu công nghiệp và khu vực sân bay; mỗi địa chỉ cho quãng đường khác nhau. Chọn đúng nơi xe đón thay vì dùng tên khu vực chung.","Vũng Tàu cũng cần địa chỉ cuối: khách sạn, Bãi Sau, Bãi Trước hoặc nơi làm việc."],trip:{heading:"Tuyến ngắn, điểm đón trả vẫn quyết định giá",paragraphs:["Nhập điểm đón, điểm trả và giờ đi để hệ thống tính chuyến thực tế."],items:["Chọn khứ hồi nếu đã có lịch về.","Ghi rõ cổng công ty hoặc khu vực đón sân bay nếu cần."]},price:"Chưa có bảng giá riêng Long Thành – Vũng Tàu. Giá Sài Gòn ↔ Vũng Tàu không phải giá cố định cho tuyến này.",places:["Đón tại nhà, khu công nghiệp hoặc điểm hẹn Long Thành.","Trả tại khách sạn, bãi biển hoặc địa chỉ Vũng Tàu."],useCases:["Phù hợp công tác, chuyên gia và nghỉ biển."],faqs:[{question:"Đón gần sân bay Long Thành?",answer:"Nhập đúng điểm đón hoặc trao đổi vị trí cụ thể."},{question:"Đi trong ngày?",answer:"Chọn khứ hồi và giờ về."},{question:"Giá Sài Gòn có áp dụng?",answer:"Không, hãy xem báo giá Long Thành thực tế."}],links:[{path:"/thue-xe-tu-quan-1-di-vung-tau",label:"Xe Quận 1 đi Vũng Tàu"},{path:"/vung-tau",label:"Xe đi Vũng Tàu"},{path:"/xe-dua-don-san-bay",label:"Xe đưa đón sân bay"}],cta:"Nhập điểm đón Long Thành và nơi trả Vũng Tàu để xem giá."}),
  "thue-xe-tu-quan-1-di-vung-tau": routeEditorial({title:"Thuê xe Quận 1 đi Vũng Tàu: giá tham khảo từ Sài Gòn",description:"Xe riêng Quận 1 đi Vũng Tàu cho khách sạn, văn phòng và gia đình. Xem giá theo địa chỉ đón trả và lịch đi.",h1:"Thuê xe từ Quận 1 đi Vũng Tàu",intro:["Từ Quận 1, điểm đón thường là khách sạn, căn hộ hoặc văn phòng. Ghi rõ sảnh, cổng hoặc tên tòa nhà để dễ gặp xe.","Nếu nhóm đi biển cuối tuần, hãy chốt số vali và giờ quay về trước khi chọn chuyến khứ hồi."],trip:{heading:"Từ trung tâm thành phố ra biển",paragraphs:["Nhập địa chỉ đón Quận 1 và điểm trả cụ thể ở Vũng Tàu để báo giá đúng."],items:["Thêm điểm đón bạn bè trước khi xem giá.","Chọn xe phù hợp số người và hành lý."]},price:"Giá tham khảo Sài Gòn ↔ Vũng Tàu một chiều: xe 5 chỗ 700.000đ, xe 7 chỗ 790.000đ. Giá thực tế thay đổi theo điểm đón/trả và lịch chuyến.",places:["Đón tại khách sạn, văn phòng hoặc căn hộ Quận 1.","Trả tại khách sạn, villa, Bãi Sau hoặc địa chỉ cụ thể."],useCases:["Phù hợp khách du lịch, công tác và gia đình."],faqs:[{question:"Giá tham khảo đã bao gồm mọi điểm ghé?",answer:"Không, điểm ghé cần được nhập để báo giá đúng."},{question:"Có đưa đón khách sạn?",answer:"Chọn đúng địa chỉ và điểm gặp tại khách sạn."},{question:"Về muộn thì sao?",answer:"Chốt giờ khứ hồi hoặc trao đổi trước khi đặt."}],links:[{path:"/thue-xe-phuong-phu-nhuan-di-vung-tau",label:"Xe Phú Nhuận đi Vũng Tàu"},{path:"/xe-tu-nha-ga-t3-di-vung-tau",label:"Xe nhà ga T3 đi Vũng Tàu"},{path:"/vung-tau",label:"Xe đi Vũng Tàu"}],cta:"Nhập địa chỉ Quận 1 và nơi trả để xem giá xe đi Vũng Tàu."}),
  "xe-dua-don-resort-long-hai": routeEditorial({title:"Xe đưa đón resort Long Hải: theo giờ check-in",description:"Đặt xe riêng đi resort Long Hải từ TP.HCM. Chọn điểm đón, tên resort và giờ về để xem giá theo chuyến.",h1:"Xe đưa đón resort Long Hải",intro:["Với chuyến Long Hải, tên resort và giờ nhận phòng quan trọng hơn việc chỉ chọn tên thị trấn. Chọn đúng địa chỉ để hành trình không dừng ở một điểm gần đó.","Nhóm gia đình nên tính số vali, đồ biển và giờ check-out khi chọn xe."],trip:{heading:"Chuyến resort theo lịch nghỉ dưỡng",paragraphs:["Điểm đón TP.HCM và resort/khách sạn Long Hải quyết định quãng đường hiển thị."],items:["Chọn khứ hồi khi đã biết giờ về.","Không mặc định xe chờ trong thời gian lưu trú."]},price:"Chưa có bảng giá xác thực riêng cho resort Long Hải. Xem giá theo điểm đón, nơi lưu trú, xe và lịch khứ hồi.",places:["Đón tại nhà, khách sạn hoặc văn phòng TP.HCM.","Trả tại resort/khách sạn Long Hải đã chọn."],useCases:["Phù hợp nghỉ dưỡng, họp nhóm và cuối tuần."],faqs:[{question:"Có đón tại nhiều nhà?",answer:"Khai báo các điểm đón để xem giá đúng."},{question:"Nếu check-out trễ?",answer:"Cập nhật giờ về hoặc trao đổi hỗ trợ trước."},{question:"Chọn xe bao nhiêu chỗ?",answer:"Dựa trên người và hành lý."}],links:[{path:"/xe-di-lan-rung-resort-phuoc-hai",label:"Xe đi Lan Rừng Resort"},{path:"/dat-xe-di-carmelina-beach-resort",label:"Xe đi Carmelina"},{path:"/long-hai",label:"Xe đi Long Hải"}],cta:"Nhập tên resort Long Hải và giờ check-in để xem giá."}),
  "thue-xe-cu-chi-di-phan-thiet": routeEditorial({title:"Thuê xe Củ Chi đi Phan Thiết: chốt khách sạn hoặc resort",description:"Xe riêng Củ Chi đi Phan Thiết cho du lịch, công tác và gia đình. Nhập địa chỉ lưu trú, lịch đi và xe để xem giá.",h1:"Thuê xe Củ Chi đi Phan Thiết",intro:["Phan Thiết có nhiều điểm trả như trung tâm, Mũi Né và resort ven biển; chọn đúng nơi lưu trú sẽ cho báo giá chính xác hơn.","Nếu đi cuối tuần, chốt giờ xuất phát, số vali và lịch về trước khi đặt xe."],trip:{heading:"Đi Phan Thiết theo điểm lưu trú",paragraphs:["Địa chỉ đón ở Củ Chi và khách sạn/resort Phan Thiết được dùng để tính hành trình."],items:["Ghi điểm ghé nếu đón thêm người.","Chọn xe theo hành khách và hành lý."]},price:"Poster Sài Gòn ↔ Phan Thiết ghi tham khảo 1.140.000đ xe 5 chỗ và 1.300.000đ xe 7 chỗ một chiều. Củ Chi là điểm đón riêng nên cần xem giá thực tế.",places:["Đón tại nhà hoặc văn phòng Củ Chi.","Trả tại khách sạn, resort hay địa chỉ cụ thể Phan Thiết."],useCases:["Phù hợp nghỉ biển, công tác và chuyến gia đình."],faqs:[{question:"Giá Sài Gòn có áp dụng Củ Chi?",answer:"Không mặc định; đây chỉ là tham khảo."},{question:"Đi Mũi Né có cùng giá?",answer:"Chọn đúng điểm trả để xem giá."},{question:"Có khứ hồi không?",answer:"Có khi đã có lịch về."}],links:[{path:"/phan-thiet",label:"Xe đi Phan Thiết"},{path:"/mui-ne",label:"Xe đi Mũi Né"},{path:"/thue-xe-di-tinh",label:"Thuê xe đi tỉnh"}],cta:"Nhập địa chỉ Củ Chi và nơi lưu trú Phan Thiết để xem giá."}),
  "thue-xe-tu-san-bay-tan-son-nhat-di-can-tho": routeEditorial({title:"Xe sân bay Tân Sơn Nhất đi Cần Thơ: theo giờ hạ cánh",description:"Đặt xe riêng từ sân bay Tân Sơn Nhất đi Cần Thơ. Nhập giờ bay, số hành lý và địa chỉ trả để xem giá theo chuyến.",h1:"Xe từ sân bay Tân Sơn Nhất đi Cần Thơ",intro:["Từ sân bay đi Cần Thơ là chuyến dài nên giờ hạ cánh, hành lý và điểm trả cuối cần được chốt trước. Gửi số chuyến bay để thuận tiện phối hợp điểm gặp.","Cần Thơ có nhiều khu vực; chọn đúng khách sạn, nhà riêng hoặc điểm làm việc thay vì chỉ nhập tên thành phố."],trip:{heading:"Sau chuyến bay, đi thẳng về Cần Thơ",paragraphs:["Dự phòng thời gian lấy hành lý và nhập địa chỉ trả chính xác trước khi xem giá."],items:["Chọn xe phù hợp người và vali.","Chọn khứ hồi khi đã có lịch quay lại sân bay."]},price:"Poster Sài Gòn ↔ Cần Thơ một chiều tham khảo: xe 5 chỗ 1.030.000đ, xe 7 chỗ 1.170.000đ. Sân bay là điểm đón đặc thù nên xem giá thực tế trước khi xác nhận.",places:["Đón tại điểm hẹn sân bay Tân Sơn Nhất.","Trả tại nhà, khách sạn hoặc địa chỉ Cần Thơ."],useCases:["Phù hợp khách vừa hạ cánh, về quê và công tác."],faqs:[{question:"Giá poster có áp dụng sân bay?",answer:"Không mặc định; đây là mức tham khảo Sài Gòn ↔ Cần Thơ."},{question:"Máy bay trễ?",answer:"Báo hỗ trợ sớm kèm số chuyến bay."},{question:"Có ghé thêm điểm?",answer:"Khai báo điểm ghé để báo giá đúng."}],links:[{path:"/can-tho",label:"Xe đi Cần Thơ"},{path:"/don-san-bay-tan-son-nhat-di-ben-tre",label:"Xe sân bay đi Bến Tre"},{path:"/xe-dua-don-san-bay",label:"Xe đưa đón sân bay"}],cta:"Nhập giờ hạ cánh và địa chỉ Cần Thơ để xem giá."}),
  "xe-tu-nha-ga-t3-di-vung-tau": routeEditorial({title:"Xe nhà ga T3 đi Vũng Tàu: chủ động sau chuyến bay",description:"Đặt xe riêng từ nhà ga T3 Tân Sơn Nhất đi Vũng Tàu. Nhập giờ bay, hành lý và nơi trả để xem giá theo hành trình.",h1:"Xe từ nhà ga T3 đi Vũng Tàu",intro:["Nhà ga T3 là điểm đón cụ thể, vì vậy cần xác nhận giờ hạ cánh và khu vực gặp xe thay vì áp dụng giờ đi từ trung tâm thành phố.","Điểm trả ở Vũng Tàu có thể là khách sạn, nhà người thân hay bãi biển; hãy chọn đúng địa chỉ."],trip:{heading:"Đón tại T3, trả thẳng Vũng Tàu",paragraphs:["Dự phòng thời gian lấy hành lý và gửi số chuyến bay để hỗ trợ phối hợp khi có thay đổi."],items:["Chọn xe theo số người và vali.","Khứ hồi cần giờ quay lại T3."]},price:"Giá Sài Gòn ↔ Vũng Tàu tham khảo là 700.000đ xe 5 chỗ và 790.000đ xe 7 chỗ một chiều. Nhà ga T3 có điểm đón riêng nên xem báo giá thực tế.",places:["Đón ở điểm hẹn được xác nhận tại nhà ga T3.","Trả tại khách sạn hoặc địa chỉ cụ thể Vũng Tàu."],useCases:["Phù hợp khách bay nội địa, công tác và nghỉ biển."],faqs:[{question:"Có cần số chuyến bay?",answer:"Nên gửi để hỗ trợ theo dõi thay đổi."},{question:"Giá Sài Gòn áp dụng T3?",answer:"Không mặc định; đây là giá tham khảo."},{question:"Đặt cho gia đình nhiều vali?",answer:"Chọn xe theo cả người và hành lý."}],links:[{path:"/thue-xe-tu-quan-1-di-vung-tau",label:"Xe Quận 1 đi Vũng Tàu"},{path:"/xe-dua-don-san-bay",label:"Xe đưa đón sân bay"},{path:"/vung-tau",label:"Xe đi Vũng Tàu"}],cta:"Nhập giờ hạ cánh T3 và địa chỉ Vũng Tàu để xem giá."}),
  "xe-tu-ben-xe-mien-dong-di-ho-tram": routeEditorial({title:"Xe Bến xe Miền Đông đi Hồ Tràm: đến đúng resort, villa",description:"Đặt xe riêng từ Bến xe Miền Đông đi Hồ Tràm. Chọn điểm đón, nơi lưu trú và giờ về để xem giá chuyến đi.",h1:"Xe từ Bến xe Miền Đông đi Hồ Tràm",intro:["Bến xe Miền Đông có khu vực đón rộng; hãy chốt đúng cổng hoặc điểm gặp trước khi đến. Tại Hồ Tràm, chọn tên resort, villa hoặc ghim vị trí thay vì chỉ chọn khu vực.","Chuyến cuối tuần nên tính hành lý, giờ nhận phòng và check-out từ đầu."],trip:{heading:"Từ bến xe đến nơi nghỉ ở Hồ Tràm",paragraphs:["Địa chỉ đón và nơi lưu trú cụ thể giúp tính quãng đường, thời gian và giá chính xác."],items:["Gửi điểm gặp dễ nhận diện tại bến xe.","Chọn khứ hồi khi đã chốt giờ về."]},price:"Chưa có bảng giá xác thực riêng Bến xe Miền Đông – Hồ Tràm. Giá phụ thuộc điểm gặp, resort/villa, loại xe và lịch đi.",places:["Đón tại cổng hoặc điểm hẹn Bến xe Miền Đông.","Trả tại resort, villa hoặc địa chỉ Hồ Tràm cụ thể."],useCases:["Phù hợp nối chuyến, nghỉ dưỡng gia đình và nhóm bạn."],faqs:[{question:"Đón ở cổng nào?",answer:"Thống nhất điểm gặp rõ ràng trước chuyến."},{question:"Hồ Tràm rộng, chọn sao?",answer:"Chọn đúng resort/villa hoặc ghim vị trí."},{question:"Có chờ check-out?",answer:"Cần chốt lịch khứ hồi hoặc trao đổi thời gian chờ."}],links:[{path:"/ho-tram",label:"Xe đi Hồ Tràm"},{path:"/dat-xe-di-carmelina-beach-resort",label:"Xe đi Carmelina"},{path:"/xe-dua-don-resort-long-hai",label:"Xe resort Long Hải"}],cta:"Nhập điểm gặp ở bến xe và nơi lưu trú Hồ Tràm để xem giá."}),
};

export function applySeoRouteEditorial(route) {
  const editorial = editorialByPath[route.path];
  if (!editorial) return route;
  return { ...route, title: editorial.title, description: editorial.description, editorial };
}
