-- AlterEnum
ALTER TYPE "CarType" ADD VALUE 'CAR_16';

-- AlterTable
ALTER TABLE "PricingConfig" ADD COLUMN     "baseFare" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isActive" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "minFare" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "overnightFee" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "pricePerHour" INTEGER NOT NULL DEFAULT 0,
ALTER COLUMN "pricePerKm" SET DEFAULT 0;
