-- AlterTable
ALTER TABLE "PricingConfig" ADD COLUMN     "overnightTriggerHours" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN     "overnightTriggerKm" INTEGER NOT NULL DEFAULT 600,
ALTER COLUMN "pricePerKm" DROP DEFAULT,
ALTER COLUMN "baseFare" DROP DEFAULT,
ALTER COLUMN "minFare" DROP DEFAULT,
ALTER COLUMN "overnightFee" DROP DEFAULT,
ALTER COLUMN "pricePerHour" DROP DEFAULT;
